import os
import re
import subprocess
import sys
import asyncio
from typing import Dict, Any, List, Optional, Callable
from services.testing.project_analyzer import ProjectAnalyzer
from services.testing.test_detector import TestDetector
from services.testing.gemini_client import GeminiClient
from services.testing.prompt_builder import PromptBuilder
from services.testing.test_validator import TestValidator

class TestGenerator:
    def __init__(self):
        self.analyzer = ProjectAnalyzer()
        self.detector = TestDetector()
        self.client = GeminiClient()
        self.prompt_builder = PromptBuilder()
        self.validator = TestValidator()
        # Max retries for auto-correction loop, configurable via env
        self.max_retries = int(os.getenv('TEST_CORRECTION_MAX_RETRIES', '3'))
        # Compilation timeout in seconds
        self.compile_timeout = int(os.getenv('TEST_COMPILE_TIMEOUT', '120'))

    def _is_method_covered(self, method_name: str, existing_test_methods: List[str]) -> bool:
        pm_norm = re.sub(r'[^a-zA-Z0-9]', '', method_name).lower()
        for tm in existing_test_methods:
            tm_norm = re.sub(r'[^a-zA-Z0-9]', '', tm).lower()
            if pm_norm in tm_norm:
                return True
        return False

    def _get_uncovered_methods(self, production_methods: List[Dict[str, Any]], existing_test_methods: List[str]) -> List[Dict[str, Any]]:
        uncovered = []
        for pm in production_methods:
            pm_name = pm.get("name", "")
            if not pm_name:
                continue
            if not self._is_method_covered(pm_name, existing_test_methods):
                uncovered.append(pm)
        return uncovered

    def _merge_test_methods(self, existing_code: str, new_imports: List[str], new_methods_code: str) -> str:
        """
        Merge new test methods and imports into the existing test class code.
        """
        # 1. Merge imports
        existing_imports = re.findall(r'import\s+([\w\.\*]+);', existing_code)
        existing_imports_set = {imp.strip() for imp in existing_imports}
        
        imports_to_add = []
        for imp in new_imports:
            m = re.search(r'import\s+([\w\.\*]+);', imp)
            if m:
                imp_name = m.group(1).strip()
                if imp_name not in existing_imports_set:
                    imports_to_add.append(imp.strip())
            
        merged_code = existing_code
        if imports_to_add:
            imports_block = "\n".join(imports_to_add) + "\n"
            package_match = re.search(r'package\s+([\w\.]+);', merged_code)
            if package_match:
                insert_pos = package_match.end()
                merged_code = merged_code[:insert_pos] + "\n" + imports_block + merged_code[insert_pos:]
            else:
                class_decl = re.search(r'(?:public\s+)?class\s+\w+', merged_code)
                if class_decl:
                    insert_pos = class_decl.start()
                    merged_code = merged_code[:insert_pos] + imports_block + "\n" + merged_code[insert_pos:]
                else:
                    merged_code = imports_block + "\n" + merged_code

        # 2. Merge test methods before the last closing brace '}' of the class
        cleaned_methods = new_methods_code.strip()
        
        # Clean any class wrappers generated by Gemini
        cleaned_methods = re.sub(r'public\s+class\s+\w+\s*(?:extends\s+\w+)?\s*(?:implements\s+[\w\s,]+)?\s*\{', '', cleaned_methods)
        cleaned_methods = re.sub(r'package\s+[\w\.]+;', '', cleaned_methods)
        cleaned_methods = re.sub(r'import\s+[^;]+;', '', cleaned_methods)
        
        last_brace_pos = merged_code.rfind('}')
        if last_brace_pos != -1:
            merged_code = merged_code[:last_brace_pos] + "\n" + cleaned_methods + "\n" + merged_code[last_brace_pos:]
            
        return merged_code

    def _get_class_meta_dict(self, class_meta: Any) -> Dict[str, Any]:
        if isinstance(class_meta, dict):
            return class_meta
        from dataclasses import asdict
        if hasattr(class_meta, "__dataclass_fields__"):
            return asdict(class_meta)
        if hasattr(class_meta, "to_dict"):
            return class_meta.to_dict()
        return {}

    async def generate_tests_for_project(
        self,
        project_path: str,
        progress_callback: Optional[Callable[[int, int, str], None]] = None,
        log_callback: Optional[Callable[[str], None]] = None
    ) -> Dict[str, Any]:
        """
        Main entry point to scan and generate JUnit test cases for all uncovered classes.
        Uses concurrent LLM calls and a batch compile-repair loop to verify code.
        """
        result = {
            "success": True,
            "tests_generated": 0,
            "generated_files": [],
            "correction_attempts": 0,
            "message": "No tests needed or generated."
        }

        def log_msg(msg: str):
            if log_callback:
                log_callback(msg)
            print(msg)

        try:
            # 1. Analyze Project
            analysis = await self.analyzer.analyze_project(project_path)
            
            # 2. Detect Existing Tests
            detection = await self.detector.detect_tests(project_path)
            
            # Identify all production classes to process (excluding interfaces that are not repositories)
            production_classes = []
            for file_path, class_meta in analysis.all_classes.items():
                class_name = getattr(class_meta, "class_name", "")
                if not class_name:
                    continue
                is_interface = getattr(class_meta, "is_interface", False)
                is_repository = getattr(class_meta, "is_repository", False)
                if is_interface and not is_repository:
                    continue
                production_classes.append((file_path, class_meta))

            if not production_classes:
                result["message"] = "No production classes found to test."
                log_msg(f"[Testing] {result['message']}")
                return result

            # Log existing test classes count
            existing_test_classes_count = len(detection.test_classes)
            log_msg(f"[Testing] Existing test classes detected: {existing_test_classes_count}")

            # Determine build tool for compilation check
            build_tool = getattr(analysis, "build_tool", "none")
            total_classes = len(production_classes)

            # Concurrent Generation Phase
            sem = asyncio.Semaphore(5)
            backups = {}
            generated_classes_info = []

            async def generate_for_class(file_path: str, class_meta: Any) -> Optional[Dict[str, Any]]:
                class_name = getattr(class_meta, "class_name", "")
                
                # Determine test file path by replacing src/main/java with src/test/java
                test_file_path = file_path.replace(os.path.join("src", "main", "java"), os.path.join("src", "test", "java"))
                test_file_path = test_file_path.replace(os.path.join("src", "main", "java").replace("\\", "/"), os.path.join("src", "test", "java"))
                dir_name = os.path.dirname(test_file_path)
                test_file_path = os.path.join(dir_name, f"{class_name}Test.java")

                # Read production source
                try:
                    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                        java_source = f.read()
                except Exception as e:
                    log_msg(f"[Testing] Failed to read source file {file_path}: {e}")
                    return None

                # Backup existing test file if it exists
                if os.path.exists(test_file_path):
                    try:
                        with open(test_file_path, "r", encoding="utf-8", errors="ignore") as f:
                            backups[test_file_path] = f.read()
                    except Exception as e:
                        log_msg(f"[Testing] Error backing up existing test {test_file_path}: {e}")
                        return None
                else:
                    backups[test_file_path] = None

                async with sem:
                    try:
                        # Case 1: Test file does NOT exist
                        if backups[test_file_path] is None:
                            log_msg(f"[Testing] Generating tests for {class_name}...")
                            prompt = self.prompt_builder.build_prompt(java_source, class_name, class_meta)
                            generated_code = await self.client.generate_test(prompt, class_meta)
                            
                            cleaned_code = self.validator.clean_and_validate(generated_code, class_name, class_meta)
                            if not cleaned_code:
                                log_msg(f"[Testing] LLM generation failed or was invalid for {class_name}. Using fallback code generator...")
                                from services.testing.test_code_generator import TestCodeGenerator
                                cleaned_code = TestCodeGenerator.generate_test_code(self._get_class_meta_dict(class_meta))

                            os.makedirs(os.path.dirname(test_file_path), exist_ok=True)
                            with open(test_file_path, "w", encoding="utf-8") as f:
                                f.write(cleaned_code)
                                
                            log_msg(f"[Testing] Generated {class_name}Test.java")

                        # Case 2: Test file ALREADY exists
                        else:
                            log_msg(f"[Testing] Test file already exists for {class_name}. Checking coverage...")
                            test_class_info = self.detector._parse_test_file(test_file_path, f"{class_name}Test")
                            existing_test_methods = []
                            if test_class_info and test_class_info.test_methods:
                                existing_test_methods = [tm.name for tm in test_class_info.test_methods]

                            production_methods = getattr(class_meta, "methods", [])
                            uncovered = self._get_uncovered_methods(production_methods, existing_test_methods)

                            if not uncovered:
                                log_msg(f"[Testing] Existing complete test suite for {class_name}. Skipping.")
                                return None

                            uncovered_names = [m["name"] for m in uncovered]
                            log_msg(f"[Testing] Partial coverage detected for {class_name}. Generating tests for uncovered methods: {', '.join(uncovered_names)}")

                            # Ask Gemini to generate only the missing test methods
                            additional_code = await self.client.generate_additional_test_methods(
                                production_source=java_source,
                                existing_test_source=backups[test_file_path],
                                uncovered_methods=uncovered_names,
                                class_meta=self._get_class_meta_dict(class_meta)
                            )

                            # Clean and merge
                            cleaned_additional = self.client._clean_generated_code(additional_code)
                            imports = []
                            methods_code = cleaned_additional
                            
                            if "// TEST METHODS" in cleaned_additional:
                                parts = cleaned_additional.split("// TEST METHODS")
                                imports_part = parts[0]
                                methods_code = parts[1].strip()
                                for line in imports_part.splitlines():
                                    if line.strip().startswith("import "):
                                        imports.append(line.strip())
                            else:
                                for line in cleaned_additional.splitlines():
                                    if line.strip().startswith("import "):
                                        imports.append(line.strip())
                                methods_code = re.sub(r'import\s+[^;]+;', '', methods_code)
                                methods_code = re.sub(r'public\s+class\s+\w+\s*\{', '', methods_code)
                                if methods_code.strip().endswith('}'):
                                    methods_code = methods_code.strip()[:-1].strip()

                            merged_code = self._merge_test_methods(backups[test_file_path], imports, methods_code)
                            
                            with open(test_file_path, "w", encoding="utf-8") as f:
                                f.write(merged_code)

                            log_msg(f"[Testing] Merged {len(uncovered)} new test methods into {class_name}Test.java")

                        return {
                            "file_path": file_path,
                            "test_file_path": test_file_path,
                            "class_name": class_name,
                            "class_meta": self._get_class_meta_dict(class_meta),
                            "java_source": java_source
                        }

                    except Exception as class_err:
                        log_msg(f"[Testing] Error generating/merging tests for class {class_name}: {class_err}")
                        # Revert immediately on generation failure
                        if backups[test_file_path] is not None:
                            with open(test_file_path, "w", encoding="utf-8") as f:
                                f.write(backups[test_file_path])
                        elif os.path.exists(test_file_path):
                            try:
                                os.remove(test_file_path)
                            except:
                                pass
                        return None

            # Run parallel generation tasks
            tasks = [generate_for_class(file_path, class_meta) for file_path, class_meta in production_classes]
            completed_results = await asyncio.gather(*tasks)
            generated_classes_info = [r for r in completed_results if r is not None]

            if progress_callback:
                progress_callback(total_classes, total_classes, "Test generation completed. Starting batch compilation verification...")

            # Batch Compilation & Repair Loop Phase
            total_correction_attempts = 0
            failing_classes = list(generated_classes_info)

            for attempt in range(self.max_retries):
                if not failing_classes:
                    break

                compiles, build_output = await self._check_project_compilation(project_path, build_tool)
                if compiles:
                    log_msg("[Testing] Project compiled successfully!")
                    failing_classes = []
                    break

                log_msg(f"[Testing] Project compilation failed (attempt {attempt + 1}/{self.max_retries}). Analyzing compiler errors...")
                
                still_failing = []
                repair_tasks = []

                async def repair_class(info: Dict[str, Any], compiler_errors_for_class: str) -> Optional[Dict[str, Any]]:
                    test_file_path = info["test_file_path"]
                    class_name = info["class_name"]
                    java_source = info["java_source"]
                    class_meta = info["class_meta"]
                    
                    try:
                        with open(test_file_path, "r", encoding="utf-8", errors="ignore") as f:
                            current_test_code = f.read()
                    except Exception:
                        return None
                    
                    log_msg(f"[Testing] Repairing compilation errors in {class_name}Test.java...")
                    fixed_code = await self.client.fix_compilation_errors(
                        production_source=java_source,
                        generated_test=current_test_code,
                        compiler_errors=compiler_errors_for_class,
                        class_meta=class_meta
                    )
                    
                    if fixed_code:
                        cleaned_fixed = self.validator.clean_and_validate(fixed_code, class_name, class_meta)
                        if cleaned_fixed:
                            with open(test_file_path, "w", encoding="utf-8") as f:
                                f.write(cleaned_fixed)
                            return info
                    return None

                for info in failing_classes:
                    test_file_path = info["test_file_path"]
                    test_file_basename = os.path.basename(test_file_path)
                    
                    # Extract error lines matching this file
                    error_lines = [
                        line for line in build_output.splitlines()
                        if test_file_basename.lower() in line.lower()
                    ]
                    
                    if error_lines:
                        total_correction_attempts += 1
                        compiler_errors_for_class = "\n".join(error_lines)
                        repair_tasks.append(repair_class(info, compiler_errors_for_class))
                        still_failing.append(info)
                    else:
                        log_msg(f"[Testing] {info['class_name']}Test.java compiled successfully.")

                if not repair_tasks:
                    log_msg("[Testing] Compilation errors did not map to any generated tests. Stopping repair loop.")
                    break

                # Execute repairs concurrently
                repaired_results = await asyncio.gather(*repair_tasks)
                failing_classes = still_failing

            # Final verification of compilation, cleanup failed classes
            compiles, build_output = await self._check_project_compilation(project_path, build_tool)
            if not compiles:
                for info in generated_classes_info:
                    test_file_path = info["test_file_path"]
                    test_file_basename = os.path.basename(test_file_path)
                    error_lines = [
                        line for line in build_output.splitlines()
                        if test_file_basename.lower() in line.lower()
                    ]
                    if error_lines:
                        log_msg(f"[Testing] Discarding {info['class_name']}Test.java due to unresolved compilation errors.")
                        if backups[test_file_path] is not None:
                            with open(test_file_path, "w", encoding="utf-8") as f:
                                f.write(backups[test_file_path])
                        else:
                            try:
                                os.remove(test_file_path)
                            except:
                                pass

            # Batch Execution Verification Phase
            log_msg("[Testing] Verifying execution of remaining generated tests...")
            from services.testing.test_execution_service import TestExecutionService
            executor = TestExecutionService()
            exec_result = await executor.execute_tests(project_path, build_tool)
            log_msg(f"[Testing] Test execution complete. Message: {exec_result.get('message', '')}")

            # Filter out any tests that failed execution
            for info in generated_classes_info:
                test_file_path = info["test_file_path"]
                if not os.path.exists(test_file_path):
                    continue

                class_name = info["class_name"]
                package_name = info["class_meta"].get("package_name", "")
                
                # Check for test execution failures in Surefire/Gradle reports
                failures_str = self._parse_test_execution_failure(project_path, class_name, package_name, build_tool)
                if failures_str and "no XML test report was found" not in failures_str:
                    log_msg(f"[Testing] Discarding {class_name}Test.java due to test execution failures:\n{failures_str[:300]}")
                    if backups[test_file_path] is not None:
                        with open(test_file_path, "w", encoding="utf-8") as f:
                            f.write(backups[test_file_path])
                    else:
                        try:
                            os.remove(test_file_path)
                        except:
                            pass

            # Make sure we are compile-clean at the very end
            compiles, build_output = await self._check_project_compilation(project_path, build_tool)
            if not compiles:
                log_msg("[Testing] Warning: Project compilation is still broken. Reverting all remaining generated tests.")
                for info in generated_classes_info:
                    test_file_path = info["test_file_path"]
                    if backups[test_file_path] is not None:
                        with open(test_file_path, "w", encoding="utf-8") as f:
                            f.write(backups[test_file_path])
                    else:
                        try:
                            os.remove(test_file_path)
                        except:
                            pass
                result["tests_generated"] = 0
                return result

            # Count successfully generated and verified files
            kept_count = 0
            for info in generated_classes_info:
                test_file_path = info["test_file_path"]
                if os.path.exists(test_file_path):
                    is_modified = True
                    if backups[test_file_path] is not None:
                        with open(test_file_path, "r", encoding="utf-8", errors="ignore") as f:
                            current = f.read()
                        if current == backups[test_file_path]:
                            is_modified = False
                    if is_modified:
                        kept_count += 1
                        result["generated_files"].append(test_file_path)

            result["tests_generated"] = kept_count
            result["correction_attempts"] = total_correction_attempts
            result["message"] = f"Generated/merged {kept_count} JUnit 5 test classes. Auto-correction attempts: {total_correction_attempts}."

        except Exception as e:
            result["success"] = False
            result["message"] = f"Error in test generation workflow: {e}"
            print(f"Error in TestGenerator: {e}")
            import traceback
            traceback.print_exc()

        return result

    async def _check_project_compilation(self, project_path: str, build_tool: str) -> tuple:
        """
        Compiles the project using Maven or Gradle to check for errors.
        Returns (compiles: bool, stdout_stderr_output: str).
        """
        try:
            is_windows = sys.platform == "win32"
            cmd = []
            
            if build_tool == "maven":
                mvnw_cmd_path = os.path.join(project_path, "mvnw.cmd")
                mvnw_sh_path = os.path.join(project_path, "mvnw")
                if is_windows and os.path.exists(mvnw_cmd_path):
                    cmd = [".\\mvnw.cmd", "test-compile"]
                elif not is_windows and os.path.exists(mvnw_sh_path):
                    cmd = ["./mvnw", "test-compile"]
                else:
                    cmd = ["mvn", "test-compile"]
            elif build_tool == "gradle":
                gradlew_bat_path = os.path.join(project_path, "gradlew.bat")
                gradlew_sh_path = os.path.join(project_path, "gradlew")
                if is_windows and os.path.exists(gradlew_bat_path):
                    cmd = [".\\gradlew.bat", "testClasses"]
                elif not is_windows and os.path.exists(gradlew_sh_path):
                    cmd = ["./gradlew", "testClasses"]
                else:
                    cmd = ["gradle", "testClasses"]
            else:
                return True, ""

            cmd_str = " ".join(cmd)
            print(f"Running batch compilation check command: {cmd_str}")
            
            process = await asyncio.create_subprocess_shell(
                cmd_str,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=project_path
            )
            
            try:
                stdout_bytes, stderr_bytes = await asyncio.wait_for(process.communicate(), timeout=self.compile_timeout)
                stdout = stdout_bytes.decode('utf-8', errors='ignore')
                stderr = stderr_bytes.decode('utf-8', errors='ignore')
            except asyncio.TimeoutError:
                process.kill()
                return False, "Compilation timed out"

            full_output = stdout + "\n" + stderr
            if process.returncode == 0:
                return True, full_output
            
            return False, full_output

        except Exception as e:
            return True, f"Error during compilation check: {e}"

    def _parse_test_execution_failure(self, project_path: str, class_name: str, package_name: str, build_tool: str) -> str:
        """Parses the Surefire/Gradle XML test report to extract the failure message and stack trace"""
        xml_filename = f"TEST-{package_name}.{class_name}Test.xml" if package_name else f"TEST-{class_name}Test.xml"
        
        # Search recursively for the XML file matching this pattern
        xml_path = None
        for root, dirs, files in os.walk(project_path):
            dirs[:] = [d for d in dirs if d not in (".git", "node_modules", "venv", ".venv")]
            if xml_filename in files:
                xml_path = os.path.join(root, xml_filename)
                break
                
        if not xml_path or not os.path.exists(xml_path):
            # Fallback: look for any XML file matching *ClassNameTest.xml
            for root, dirs, files in os.walk(project_path):
                dirs[:] = [d for d in dirs if d not in (".git", "node_modules", "venv", ".venv")]
                for file in files:
                    if file.endswith(f"{class_name}Test.xml"):
                        xml_path = os.path.join(root, file)
                        break
                if xml_path:
                    break

        if not xml_path or not os.path.exists(xml_path):
            return "Test execution failed, but no XML test report was found."

        try:
            import xml.etree.ElementTree as ET
            tree = ET.parse(xml_path)
            root = tree.getroot()
            
            failures = []
            for testcase in root.findall(".//testcase"):
                name = testcase.get("name")
                for fail in testcase.findall("failure"):
                    msg = fail.get("message", "")
                    stack = fail.text or ""
                    failures.append(f"Method: {name} - Failure: {msg}\nStacktrace:\n{stack}")
                for err in testcase.findall("error"):
                    msg = err.get("message", "")
                    stack = err.text or ""
                    failures.append(f"Method: {name} - Error: {msg}\nStacktrace:\n{stack}")
            
            if failures:
                return "\n\n".join(failures)
            return ""
        except Exception as e:
            return f"Failed to parse test report XML: {e}"