import os
import re
import subprocess
import sys
import asyncio
import time
from typing import Dict, Any, List, Optional, Callable
from services.testing.project_analyzer import ProjectAnalyzer
from services.testing.test_detector import TestDetector
from services.testing.gemini_client import GeminiClient
from services.testing.prompt_builder import PromptBuilder
from services.testing.test_validator import TestValidator

class TestGenerator:
    def __init__(self):
        self.analyzer = ProjectAnalyzer()
        self.detector = TestDetector()
        self.client = GeminiClient()
        self.prompt_builder = PromptBuilder()
        self.validator = TestValidator()
        # Max retries for auto-correction loop, configurable via env
        self.max_retries = max(1, int(os.getenv('TEST_CORRECTION_MAX_RETRIES', '5')))
        # Compilation timeout in seconds
        self.compile_timeout = int(os.getenv('TEST_COMPILE_TIMEOUT', '120'))
        self.repair_timeout = float(os.getenv("TEST_REPAIR_REQUEST_TIMEOUT_SECONDS", "120"))

    def _is_method_covered(self, method_name: str, existing_test_methods: List[str]) -> bool:
        pm_norm = re.sub(r'[^a-zA-Z0-9]', '', method_name).lower()
        for tm in existing_test_methods:
            tm_norm = re.sub(r'[^a-zA-Z0-9]', '', tm).lower()
            if pm_norm in tm_norm:
                return True
        return False

    def _get_uncovered_methods(self, production_methods: List[Dict[str, Any]], existing_test_methods: List[str]) -> List[Dict[str, Any]]:
        uncovered = []
        for pm in production_methods:
            pm_name = pm.get("name", "")
            if not pm_name:
                continue
            if not self._is_method_covered(pm_name, existing_test_methods):
                uncovered.append(pm)
        return uncovered

    def _merge_test_methods(self, existing_code: str, new_imports: List[str], new_methods_code: str) -> str:
        """
        Merge new test methods and imports into the existing test class code.
        """
        # 1. Merge imports
        existing_imports = re.findall(r'import\s+([\w\.\*]+);', existing_code)
        existing_imports_set = {imp.strip() for imp in existing_imports}
        
        imports_to_add = []
        for imp in new_imports:
            m = re.search(r'import\s+([\w\.\*]+);', imp)
            if m:
                imp_name = m.group(1).strip()
                if imp_name not in existing_imports_set:
                    imports_to_add.append(imp.strip())
            
        merged_code = existing_code
        if imports_to_add:
            imports_block = "\n".join(imports_to_add) + "\n"
            package_match = re.search(r'package\s+([\w\.]+);', merged_code)
            if package_match:
                insert_pos = package_match.end()
                merged_code = merged_code[:insert_pos] + "\n" + imports_block + merged_code[insert_pos:]
            else:
                class_decl = re.search(r'(?:public\s+)?class\s+\w+', merged_code)
                if class_decl:
                    insert_pos = class_decl.start()
                    merged_code = merged_code[:insert_pos] + imports_block + "\n" + merged_code[insert_pos:]
                else:
                    merged_code = imports_block + "\n" + merged_code

        # 2. Merge test methods before the last closing brace '}' of the class
        cleaned_methods = new_methods_code.strip()
        
        # Clean any class wrappers generated by Gemini
        cleaned_methods = re.sub(r'public\s+class\s+\w+\s*(?:extends\s+\w+)?\s*(?:implements\s+[\w\s,]+)?\s*\{', '', cleaned_methods)
        cleaned_methods = re.sub(r'package\s+[\w\.]+;', '', cleaned_methods)
        cleaned_methods = re.sub(r'import\s+[^;]+;', '', cleaned_methods)
        
        last_brace_pos = merged_code.rfind('}')
        if last_brace_pos != -1:
            merged_code = merged_code[:last_brace_pos] + "\n" + cleaned_methods + "\n" + merged_code[last_brace_pos:]
            
        return merged_code

    def _get_class_meta_dict(self, class_meta: Any) -> Dict[str, Any]:
        if isinstance(class_meta, dict):
            return class_meta
        from dataclasses import asdict
        if hasattr(class_meta, "__dataclass_fields__"):
            return asdict(class_meta)
        if hasattr(class_meta, "to_dict"):
            return class_meta.to_dict()
        return {}

    async def generate_tests_for_project(
        self,
        project_path: str,
        progress_callback: Optional[Callable[[int, int, str], None]] = None,
        log_callback: Optional[Callable[[str], None]] = None
    ) -> Dict[str, Any]:
        """
        Main entry point to scan and generate JUnit test cases for all uncovered classes.
        Uses sequential LLM calls and a batch compile-repair loop to verify code.
        """
        result = {
            "success": True,
            "tests_generated": 0,
            "generated_files": [],
            "correction_attempts": 0,
            "message": "No tests needed or generated."
        }

        def log_msg(msg: str):
            if log_callback:
                log_callback(msg)
            print(msg)

        try:
            # 1. Analyze Project
            analysis = await self.analyzer.analyze_project(project_path)
            
            # 2. Detect Existing Tests
            detection = await self.detector.detect_tests(project_path)
            
            # 3. Get candidates from Test Detection Engine
            candidates = self.detector.get_test_generation_targets(analysis, detection)

            if not candidates:
                result["message"] = "No production classes found to test."
                log_msg(f"[Testing] {result['message']}")
                return result

            # Log existing test classes count
            existing_test_classes_count = len(detection.test_classes)
            log_msg(f"[Testing] Existing test classes detected: {existing_test_classes_count}")

            # Determine build tool for compilation check
            build_tool = getattr(analysis, "build_tool", "none")
            total_classes = len(candidates)

            # Sequential Generation Phase (one Java class at a time)
            backups = {}
            generated_classes_info = []

            for idx, cand in enumerate(candidates):
                file_path = cand["file_path"]
                test_class_name = cand["test_class_name"]
                uncovered_methods = cand["uncovered_methods"]
                additional = cand["additional"]
                
                class_meta = analysis.all_classes.get(file_path)
                if not class_meta:
                    continue
                class_name = getattr(class_meta, "class_name", "")
                if not class_name:
                    continue
                
                # Determine test file path by replacing src/main/java with src/test/java
                test_file_path = file_path.replace(os.path.join("src", "main", "java"), os.path.join("src", "test", "java"))
                test_file_path = test_file_path.replace(os.path.join("src", "main", "java").replace("\\", "/"), os.path.join("src", "test", "java"))
                dir_name = os.path.dirname(test_file_path)
                test_file_path = os.path.join(dir_name, f"{test_class_name}.java")

                # Read production source
                try:
                    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                        java_source = f.read()
                except Exception as e:
                    log_msg(f"[Testing] Failed to read source file {file_path}: {e}")
                    continue

                # Backup / Skip checks:
                # "Existing tests must never be overwritten."
                if os.path.exists(test_file_path):
                    log_msg(f"[Testing] Test file already exists for {test_class_name} at {test_file_path}. Skipping to prevent overwriting.")
                    continue
                else:
                    backups[test_file_path] = None

                log_msg(f"[Testing] Generating tests for {class_name} ({idx+1}/{total_classes}) -> {test_class_name}...")
                
                # Update progress
                if progress_callback:
                    progress_callback(idx, total_classes, f"Generating tests for {class_name}...")

                try:
                    prompt = self.prompt_builder.build_prompt(
                        java_source=java_source,
                        class_name=class_name,
                        class_meta=class_meta,
                        test_class_name=test_class_name,
                        uncovered_methods=uncovered_methods
                    )
                    generated_code = await self.client.generate_test(prompt, class_meta)
                    
                    cleaned_code = self.validator.clean_and_validate(generated_code, test_class_name, class_meta)
                    if not cleaned_code:
                        log_msg(f"[Testing] LLM generation failed or was invalid for {test_class_name}. Using fallback code generator...")
                        class_meta_dict = self._get_class_meta_dict(class_meta).copy()
                        # Override class_name in class_meta_dict to produce the expected test class name
                        class_meta_dict["class_name"] = test_class_name.replace("Test", "")
                        from services.testing.test_code_generator import TestCodeGenerator
                        fallback_code = TestCodeGenerator.generate_test_code(class_meta_dict)
                        cleaned_code = fallback_code.replace(f"class {class_meta_dict['class_name']}Test", f"class {test_class_name}")

                    os.makedirs(os.path.dirname(test_file_path), exist_ok=True)
                    with open(test_file_path, "w", encoding="utf-8") as f:
                        f.write(cleaned_code)
                        
                    log_msg(f"[Testing] Generated Test: {test_class_name}.java")

                    generated_info = {
                        "file_path": file_path,
                        "test_file_path": test_file_path,
                        "class_name": class_name,
                        "test_class_name": test_class_name,
                        "class_meta": self._get_class_meta_dict(class_meta),
                        "java_source": java_source
                    }

                    # Compile and repair this file immediately. A broken generated
                    # test is never allowed to contaminate later test compilation.
                    compiled, attempts = await self._compile_and_repair_generated_test(
                        project_path, build_tool, generated_info, log_msg
                    )
                    if compiled:
                        generated_info["repair_attempts"] = attempts
                        generated_classes_info.append(generated_info)
                    else:
                        log_msg(
                            f"[Testing] Discarding only unrecoverable generated test: "
                            f"{test_class_name}.java after {self.max_retries} repair attempts."
                        )
                        try:
                            os.remove(test_file_path)
                        except OSError as remove_error:
                            log_msg(f"[Testing] Could not discard {test_class_name}.java: {remove_error}")

                except Exception as class_err:
                    log_msg(f"[Testing] Error generating tests for class {class_name}: {class_err}")
                    if os.path.exists(test_file_path):
                        try:
                            os.remove(test_file_path)
                        except:
                            pass

            if progress_callback:
                progress_callback(total_classes, total_classes, "Test generation completed. Starting compilation and repair...")

            # ================================================================
            # PHASE 2: Per-file compile-repair loop
            # Each generated test is compiled, errors extracted, sent to Gemini
            # for repair, recompiled, repeated up to max_retries times.
            # Only fully-compiled tests proceed to the test run.
            # ================================================================
            total_correction_attempts = sum(i.get("repair_attempts", 0) for i in generated_classes_info)

            # Test execution and report parsing are deliberately owned by the
            # orchestration pipeline. The generator returns only verified files so
            # Maven/Gradle runs once and metrics are published only after parsing.

            # Count surviving generated files
            kept_count = 0
            for info in generated_classes_info:
                test_file_path = info["test_file_path"]
                if os.path.exists(test_file_path):
                    kept_count += 1
                    result["generated_files"].append(os.path.basename(test_file_path))

            result["tests_generated"] = kept_count
            result["correction_attempts"] = total_correction_attempts
            result["message"] = (
                f"Generated/merged {kept_count} JUnit 5 test classes. "
                f"Auto-correction attempts: {total_correction_attempts}."
            )

        except Exception as e:
            result["success"] = False
            result["message"] = f"Error in test generation workflow: {e}"
            print(f"Error in TestGenerator: {e}")
            import traceback
            traceback.print_exc()

        return result

    async def _compile_and_repair_generated_test(
        self,
        project_path: str,
        build_tool: str,
        info: Dict[str, Any],
        log_msg: Callable[[str], None],
    ) -> tuple:
        """Compile one newly generated test and repair only that file."""
        test_path = info["test_file_path"]
        test_name = os.path.basename(test_path)
        attempts = 0

        for verification in range(0, self.max_retries + 1):
            compiles, output = await self._compile_single_generated_test(
                project_path, build_tool, test_path
            )
            if compiles:
                log_msg(f"[Testing] Compilation: SUCCESS - {test_name}")
                return True, attempts

            diagnostics = self._structured_test_diagnostics(output, test_path)
            if not diagnostics:
                log_msg(
                    f"[Testing] Compilation: FAILED - {test_name}\n"
                    "[Testing] Compiler returned no file-specific diagnostics.\n"
                    f"[Testing] Build output tail:\n{output[-2000:]}"
                )
            else:
                for diagnostic in diagnostics:
                    log_msg(
                        f"[Testing] Compilation: FAILED - {test_name}\n"
                        f"[Testing] Compiler Error: Line {diagnostic['line_number']} "
                        f"{diagnostic['message']}\n"
                        f"[Testing] Surrounding code:\n{diagnostic['surrounding_code']}"
                    )

            if verification >= self.max_retries:
                return False, attempts

            attempts += 1
            log_msg(f"[Testing] Repair Attempt: {attempts}/{self.max_retries} - {test_name}")
            try:
                with open(test_path, "r", encoding="utf-8", errors="ignore") as source_file:
                    broken_test = source_file.read()
            except OSError as read_error:
                log_msg(f"[Testing] Cannot read failing test {test_name}: {read_error}")
                return False, attempts

            compiler_text = "\n".join(
                f"Line {item['line_number']}: {item['message']}\n{item['surrounding_code']}"
                for item in diagnostics
            ) or output[-4000:]
            repair_started = time.monotonic()
            failure_reason = "no usable Java repair returned"
            try:
                repaired = await asyncio.wait_for(
                    self.client.fix_compilation_errors(
                        generated_test=broken_test,
                        compiler_errors=compiler_text,
                        production_source=info["java_source"],
                        class_meta=info["class_meta"],
                    ),
                    timeout=self.repair_timeout,
                )
            except asyncio.TimeoutError:
                repaired = None
                failure_reason = f"request timed out after {self.repair_timeout:.1f}s"
            except Exception as repair_error:
                repaired = None
                failure_reason = f"request failed: {repair_error}"
            elapsed = time.monotonic() - repair_started
            if not repaired or "class " not in repaired:
                log_msg(f"[Testing] Repair Attempt {attempts}/{self.max_retries} - {test_name} - FAILED in {elapsed:.2f}s - {failure_reason}")
                continue

            cleaned = self.validator.clean_and_validate(
                repaired, info["test_class_name"], info["class_meta"]
            )
            try:
                with open(test_path, "w", encoding="utf-8") as output_file:
                    output_file.write(cleaned or repaired)
                log_msg(f"[Testing] Repair Attempt {attempts}/{self.max_retries} - {test_name} - SUCCESS in {elapsed:.2f}s")
            except OSError as write_error:
                log_msg(f"[Testing] Gemini fix could not replace {test_name}: {write_error}")
                return False, attempts

        return False, attempts

    async def _compile_single_generated_test(
        self, project_path: str, build_tool: str, test_file_path: str
    ) -> tuple:
        """Ask the build tool to compile the selected generated test file."""
        is_windows = sys.platform == "win32"
        relative = os.path.relpath(
            test_file_path, os.path.join(project_path, "src", "test", "java")
        ).replace("\\", "/")

        if build_tool == "maven":
            executable = (
                ".\\mvnw.cmd" if is_windows and os.path.exists(os.path.join(project_path, "mvnw.cmd"))
                else "./mvnw" if not is_windows and os.path.exists(os.path.join(project_path, "mvnw"))
                else "mvn"
            )
            cmd = [executable, "test-compile"]
        elif build_tool == "gradle":
            executable = (
                ".\\gradlew.bat" if is_windows and os.path.exists(os.path.join(project_path, "gradlew.bat"))
                else "./gradlew" if not is_windows and os.path.exists(os.path.join(project_path, "gradlew"))
                else "gradle"
            )
            cmd = [executable, "compileTestJava", "--no-daemon"]
        else:
            return True, "No supported build tool; per-file compilation skipped."

        isolated_files = []
        patched_file = original_build_content = None
        test_root = os.path.join(project_path, "src", "test", "java")
        try:
            # Use the installed JDK for validation, then restore the migrated target.
            from services.testing.compilation_repair import CompilationRepairService
            patched_file, original_build_content = CompilationRepairService()._patch_java_version_if_needed(project_path)

            # Build tools normally compile the entire test source set. Hide all
            # other tests temporarily so diagnostics belong only to this file.
            if os.path.isdir(test_root):
                selected = os.path.normcase(os.path.abspath(test_file_path))
                for root, _, files in os.walk(test_root):
                    for filename in files:
                        candidate = os.path.join(root, filename)
                        if filename.endswith(".java") and os.path.normcase(os.path.abspath(candidate)) != selected:
                            disabled = candidate + ".codex-disabled"
                            os.replace(candidate, disabled)
                            isolated_files.append((disabled, candidate))
            if is_windows:
                process = await asyncio.create_subprocess_shell(
                    subprocess.list2cmdline(cmd),
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                    cwd=project_path,
                )
            else:
                process = await asyncio.create_subprocess_exec(
                    *cmd,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                    cwd=project_path,
                )
            stdout, stderr = await asyncio.wait_for(
                process.communicate(), timeout=self.compile_timeout
            )
            output = stdout.decode("utf-8", errors="ignore") + "\n" + stderr.decode("utf-8", errors="ignore")
            return process.returncode == 0, output
        except asyncio.TimeoutError:
            process.kill()
            await process.wait()
            return False, f"Compilation timed out after {self.compile_timeout} seconds for {relative}."
        except OSError as execution_error:
            return False, f"Build tool execution failed for {relative}: {execution_error}"
        finally:
            if patched_file and original_build_content is not None:
                try:
                    with open(patched_file, "w", encoding="utf-8") as build_file:
                        build_file.write(original_build_content)
                except OSError as restore_build_error:
                    print(f"[Testing] CRITICAL: could not restore build file {patched_file}: {restore_build_error}")
            for disabled, original in reversed(isolated_files):
                try:
                    if os.path.exists(disabled):
                        os.replace(disabled, original)
                except OSError as restore_error:
                    print(f"[Testing] CRITICAL: could not restore isolated test {original}: {restore_error}")

    def _structured_test_diagnostics(
        self, build_output: str, test_file_path: str
    ) -> List[Dict[str, Any]]:
        """Return exact compiler diagnostics plus source context for one test."""
        filename = os.path.basename(test_file_path)
        patterns = [
            re.compile(r"(?:\[ERROR\]\s+)?(.*?\.java):\[?(\d+)(?:,\d+)?\]?\s+(?:error:\s*)?(.*)", re.I),
        ]
        parsed: List[Dict[str, Any]] = []
        seen = set()
        try:
            with open(test_file_path, "r", encoding="utf-8", errors="ignore") as source_file:
                source_lines = source_file.read().splitlines()
        except OSError:
            source_lines = []

        for raw_line in build_output.splitlines():
            if filename.lower() not in raw_line.lower():
                continue
            for pattern in patterns:
                match = pattern.search(raw_line.strip())
                if not match:
                    continue
                line_number = int(match.group(2))
                message = match.group(3).strip()
                key = (line_number, message)
                if key in seen:
                    break
                seen.add(key)
                start = max(0, line_number - 3)
                end = min(len(source_lines), line_number + 2)
                context = "\n".join(
                    f"{index + 1:>4}: {source_lines[index]}"
                    for index in range(start, end)
                )
                parsed.append({
                    "file_name": filename,
                    "line_number": line_number,
                    "message": message,
                    "surrounding_code": context,
                })
                break
        return parsed
    def _extract_error_context(self, build_output: str, filename: str) -> List[str]:
        """
        Returns all output lines related to a specific Java file.
        Includes the error line itself, surrounding '^' pointer lines, and
        any 'symbol / location' continuation lines that follow.
        """
        result_lines = []
        lines = build_output.splitlines()
        fname_lower = filename.lower()
        i = 0
        while i < len(lines):
            line = lines[i]
            if fname_lower in line.lower():
                # Capture this line
                result_lines.append(line)
                # Capture up to 4 continuation lines (^, symbol, location, note)
                j = i + 1
                while j < len(lines) and j <= i + 4:
                    next_line = lines[j].strip()
                    if (
                        next_line.startswith("^")
                        or next_line.startswith("symbol")
                        or next_line.startswith("location")
                        or next_line.startswith("note")
                        or next_line.startswith("reason")
                        or (next_line and not next_line.startswith("["))
                    ):
                        result_lines.append(lines[j])
                        j += 1
                    else:
                        break
                i = j
            else:
                i += 1
        # De-duplicate preserving order
        seen = set()
        unique = []
        for line in result_lines:
            if line not in seen:
                seen.add(line)
                unique.append(line)
        return unique

    async def _check_project_compilation(self, project_path: str, build_tool: str) -> tuple:
        """
        Compiles the project using Maven or Gradle to check for errors.
        Returns (compiles: bool, stdout_stderr_output: str).
        """
        try:
            is_windows = sys.platform == "win32"
            cmd = []
            
            if build_tool == "maven":
                mvnw_cmd_path = os.path.join(project_path, "mvnw.cmd")
                mvnw_sh_path = os.path.join(project_path, "mvnw")
                if is_windows and os.path.exists(mvnw_cmd_path):
                    cmd = [".\\mvnw.cmd", "clean", "test-compile"]
                elif not is_windows and os.path.exists(mvnw_sh_path):
                    cmd = ["./mvnw", "clean", "test-compile"]
                else:
                    cmd = ["mvn", "clean", "test-compile"]
            elif build_tool == "gradle":
                gradlew_bat_path = os.path.join(project_path, "gradlew.bat")
                gradlew_sh_path = os.path.join(project_path, "gradlew")
                if is_windows and os.path.exists(gradlew_bat_path):
                    cmd = [".\\gradlew.bat", "clean", "testClasses"]
                elif not is_windows and os.path.exists(gradlew_sh_path):
                    cmd = ["./gradlew", "clean", "testClasses"]
                else:
                    cmd = ["gradle", "clean", "testClasses"]
            else:
                return True, ""

            cmd_str = " ".join(cmd)
            print(f"Running batch compilation check command: {cmd_str}")
            
            from services.testing.compilation_repair import CompilationRepairService
            repair_service = CompilationRepairService()
            patched_file, original_content = repair_service._patch_java_version_if_needed(project_path)
            
            try:
                process = await asyncio.create_subprocess_shell(
                    cmd_str,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                    cwd=project_path
                )
                
                try:
                    stdout_bytes, stderr_bytes = await asyncio.wait_for(process.communicate(), timeout=self.compile_timeout)
                    stdout = stdout_bytes.decode('utf-8', errors='ignore')
                    stderr = stderr_bytes.decode('utf-8', errors='ignore')
                except asyncio.TimeoutError:
                    process.kill()
                    return False, "Compilation timed out"

                full_output = stdout + "\n" + stderr
                if process.returncode == 0:
                    return True, full_output
                
                return False, full_output
            finally:
                if patched_file and original_content:
                    try:
                        with open(patched_file, "w", encoding="utf-8") as f:
                            f.write(original_content)
                    except Exception as restore_err:
                        print(f"Error restoring build file during batch compile check: {restore_err}")

        except Exception as e:
            return True, f"Error during compilation check: {e}"

    def _parse_test_execution_failure(self, project_path: str, class_name: str, package_name: str, build_tool: str) -> str:
        """Parses the Surefire/Gradle XML test report to extract the failure message and stack trace"""
        xml_filename = f"TEST-{package_name}.{class_name}Test.xml" if package_name else f"TEST-{class_name}Test.xml"
        
        # Search recursively for the XML file matching this pattern
        xml_path = None
        for root, dirs, files in os.walk(project_path):
            dirs[:] = [d for d in dirs if d not in (".git", "node_modules", "venv", ".venv")]
            if xml_filename in files:
                xml_path = os.path.join(root, xml_filename)
                break
                
        if not xml_path or not os.path.exists(xml_path):
            # Fallback: look for any XML file matching *ClassNameTest.xml
            for root, dirs, files in os.walk(project_path):
                dirs[:] = [d for d in dirs if d not in (".git", "node_modules", "venv", ".venv")]
                for file in files:
                    if file.endswith(f"{class_name}Test.xml"):
                        xml_path = os.path.join(root, file)
                        break
                if xml_path:
                    break

        if not xml_path or not os.path.exists(xml_path):
            return "Test execution failed, but no XML test report was found."

        try:
            import xml.etree.ElementTree as ET
            tree = ET.parse(xml_path)
            root = tree.getroot()
            
            failures = []
            for testcase in root.findall(".//testcase"):
                name = testcase.get("name")
                for fail in testcase.findall("failure"):
                    msg = fail.get("message", "")
                    stack = fail.text or ""
                    failures.append(f"Method: {name} - Failure: {msg}\nStacktrace:\n{stack}")
                for err in testcase.findall("error"):
                    msg = err.get("message", "")
                    stack = err.text or ""
                    failures.append(f"Method: {name} - Error: {msg}\nStacktrace:\n{stack}")
            
            if failures:
                return "\n\n".join(failures)
            return ""
        except Exception as e:
            return f"Failed to parse test report XML: {e}"