import os
import re
import subprocess
import sys
import asyncio
from typing import Dict, Any, List, Optional, Callable
from services.testing.project_analyzer import ProjectAnalyzer
from services.testing.test_detector import TestDetector
from services.testing.gemini_client import GeminiClient
from services.testing.prompt_builder import PromptBuilder
from services.testing.test_validator import TestValidator

class TestGenerator:
    def __init__(self):
        self.analyzer = ProjectAnalyzer()
        self.detector = TestDetector()
        self.client = GeminiClient()
        self.prompt_builder = PromptBuilder()
        self.validator = TestValidator()
        # Max retries for auto-correction loop, configurable via env
        self.max_retries = int(os.getenv('TEST_CORRECTION_MAX_RETRIES', '3'))
        # Compilation timeout in seconds
        self.compile_timeout = int(os.getenv('TEST_COMPILE_TIMEOUT', '120'))

    def _is_method_covered(self, method_name: str, existing_test_methods: List[str]) -> bool:
        pm_norm = re.sub(r'[^a-zA-Z0-9]', '', method_name).lower()
        for tm in existing_test_methods:
            tm_norm = re.sub(r'[^a-zA-Z0-9]', '', tm).lower()
            if pm_norm in tm_norm:
                return True
        return False

    def _get_uncovered_methods(self, production_methods: List[Dict[str, Any]], existing_test_methods: List[str]) -> List[Dict[str, Any]]:
        uncovered = []
        for pm in production_methods:
            pm_name = pm.get("name", "")
            if not pm_name:
                continue
            if not self._is_method_covered(pm_name, existing_test_methods):
                uncovered.append(pm)
        return uncovered

    def _merge_test_methods(self, existing_code: str, new_imports: List[str], new_methods_code: str) -> str:
        """
        Merge new test methods and imports into the existing test class code.
        """
        # 1. Merge imports
        existing_imports = re.findall(r'import\s+([\w\.\*]+);', existing_code)
        existing_imports_set = {imp.strip() for imp in existing_imports}
        
        imports_to_add = []
        for imp in new_imports:
            m = re.search(r'import\s+([\w\.\*]+);', imp)
            if m:
                imp_name = m.group(1).strip()
                if imp_name not in existing_imports_set:
                    imports_to_add.append(imp.strip())
            
        merged_code = existing_code
        if imports_to_add:
            imports_block = "\n".join(imports_to_add) + "\n"
            package_match = re.search(r'package\s+([\w\.]+);', merged_code)
            if package_match:
                insert_pos = package_match.end()
                merged_code = merged_code[:insert_pos] + "\n" + imports_block + merged_code[insert_pos:]
            else:
                class_decl = re.search(r'(?:public\s+)?class\s+\w+', merged_code)
                if class_decl:
                    insert_pos = class_decl.start()
                    merged_code = merged_code[:insert_pos] + imports_block + "\n" + merged_code[insert_pos:]
                else:
                    merged_code = imports_block + "\n" + merged_code

        # 2. Merge test methods before the last closing brace '}' of the class
        cleaned_methods = new_methods_code.strip()
        
        # Clean any class wrappers generated by Gemini
        cleaned_methods = re.sub(r'public\s+class\s+\w+\s*(?:extends\s+\w+)?\s*(?:implements\s+[\w\s,]+)?\s*\{', '', cleaned_methods)
        cleaned_methods = re.sub(r'package\s+[\w\.]+;', '', cleaned_methods)
        cleaned_methods = re.sub(r'import\s+[^;]+;', '', cleaned_methods)
        
        last_brace_pos = merged_code.rfind('}')
        if last_brace_pos != -1:
            merged_code = merged_code[:last_brace_pos] + "\n" + cleaned_methods + "\n" + merged_code[last_brace_pos:]
            
        return merged_code

    def _get_class_meta_dict(self, class_meta: Any) -> Dict[str, Any]:
        if isinstance(class_meta, dict):
            return class_meta
        from dataclasses import asdict
        if hasattr(class_meta, "__dataclass_fields__"):
            return asdict(class_meta)
        if hasattr(class_meta, "to_dict"):
            return class_meta.to_dict()
        return {}

    async def generate_tests_for_project(
        self,
        project_path: str,
        progress_callback: Optional[Callable[[int, int, str], None]] = None,
        log_callback: Optional[Callable[[str], None]] = None
    ) -> Dict[str, Any]:
        """
        Main entry point to scan and generate JUnit test cases for all uncovered classes.
        Includes auto-correction loop: after generating each test, runs compilation and
        if errors occur, sends them back to Gemini for fixing.
        """
        result = {
            "success": True,
            "tests_generated": 0,
            "generated_files": [],
            "correction_attempts": 0,
            "message": "No tests needed or generated."
        }

        def log_msg(msg: str):
            if log_callback:
                log_callback(msg)
            print(msg)

        try:
            # 1. Analyze Project
            analysis = await self.analyzer.analyze_project(project_path)
            
            # 2. Detect Existing Tests
            detection = await self.detector.detect_tests(project_path)
            
            # Identify all production classes to process (excluding interfaces that are not repositories)
            production_classes = []
            for file_path, class_meta in analysis.all_classes.items():
                class_name = getattr(class_meta, "class_name", "")
                if not class_name:
                    continue
                is_interface = getattr(class_meta, "is_interface", False)
                is_repository = getattr(class_meta, "is_repository", False)
                if is_interface and not is_repository:
                    continue
                production_classes.append((file_path, class_meta))

            if not production_classes:
                result["message"] = "No production classes found to test."
                log_msg(f"[Testing] {result['message']}")
                return result

            # Log existing test classes count
            existing_test_classes_count = len(detection.test_classes)
            log_msg(f"[Testing] Existing test classes detected: {existing_test_classes_count}")

            generated_count = 0
            generated_files_list = []
            total_correction_attempts = 0

            # Determine build tool for compilation check
            build_tool = getattr(analysis, "build_tool", "none")

            total_classes = len(production_classes)
            completed_classes = 0

            for file_path, class_meta in production_classes:
                completed_classes += 1
                class_name = getattr(class_meta, "class_name", "")
                
                # Determine test file path by replacing src/main/java with src/test/java
                test_file_path = file_path.replace(os.path.join("src", "main", "java"), os.path.join("src", "test", "java"))
                test_file_path = test_file_path.replace(os.path.join("src", "main", "java").replace("\\", "/"), os.path.join("src", "test", "java"))
                dir_name = os.path.dirname(test_file_path)
                test_file_path = os.path.join(dir_name, f"{class_name}Test.java")

                # Read production source
                try:
                    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                        java_source = f.read()
                except Exception as e:
                    log_msg(f"[Testing] Failed to read source file {file_path}: {e}")
                    continue

                if progress_callback:
                    progress_callback(completed_classes, total_classes, f"Processing tests for {class_name}...")

                try:
                    # Case 1: Test file does NOT exist
                    if not os.path.exists(test_file_path):
                        log_msg(f"[Testing] Generating tests for {class_name}...")
                        prompt = self.prompt_builder.build_prompt(java_source, class_name, class_meta)
                        generated_code = await self.client.generate_test(prompt, class_meta)
                        
                        cleaned_code = self.validator.clean_and_validate(generated_code, class_name, class_meta)
                        if not cleaned_code:
                            # If Gemini failed to generate valid test, use fallback
                            log_msg(f"[Testing] LLM generation failed or was invalid for {class_name}. Using fallback code generator...")
                            from services.testing.test_code_generator import TestCodeGenerator
                            cleaned_code = TestCodeGenerator.generate_test_code(self._get_class_meta_dict(class_meta))

                        os.makedirs(os.path.dirname(test_file_path), exist_ok=True)
                        with open(test_file_path, "w", encoding="utf-8") as f:
                            f.write(cleaned_code)
                            
                        log_msg(f"[Testing] Generated {class_name}Test.java")
                        pkg_rel_path = os.path.relpath(test_file_path, project_path).replace("\\", "/")
                        log_msg(f"[Testing] Saved test to {pkg_rel_path}")

                    # Case 2: Test file ALREADY exists
                    else:
                        log_msg(f"[Testing] Test file already exists for {class_name}. Checking coverage...")
                        test_class_info = self.detector._parse_test_file(test_file_path, f"{class_name}Test")
                        existing_test_methods = []
                        if test_class_info and test_class_info.test_methods:
                            existing_test_methods = [tm.name for tm in test_class_info.test_methods]

                        production_methods = getattr(class_meta, "methods", [])
                        uncovered = self._get_uncovered_methods(production_methods, existing_test_methods)

                        if not uncovered:
                            log_msg(f"[Testing] Existing complete test suite for {class_name}. Skipping.")
                            continue

                        uncovered_names = [m["name"] for m in uncovered]
                        log_msg(f"[Testing] Partial coverage detected for {class_name}. Generating tests for uncovered methods: {', '.join(uncovered_names)}")

                        with open(test_file_path, "r", encoding="utf-8", errors="ignore") as f:
                            existing_test_source = f.read()

                        # Ask Gemini to generate only the missing test methods
                        additional_code = await self.client.generate_additional_test_methods(
                            production_source=java_source,
                            existing_test_source=existing_test_source,
                            uncovered_methods=uncovered_names,
                            class_meta=self._get_class_meta_dict(class_meta)
                        )

                        # Clean and merge
                        cleaned_additional = self.client._clean_generated_code(additional_code)
                        imports = []
                        methods_code = cleaned_additional
                        
                        if "// TEST METHODS" in cleaned_additional:
                            parts = cleaned_additional.split("// TEST METHODS")
                            imports_part = parts[0]
                            methods_code = parts[1].strip()
                            for line in imports_part.splitlines():
                                if line.strip().startswith("import "):
                                    imports.append(line.strip())
                        else:
                            for line in cleaned_additional.splitlines():
                                if line.strip().startswith("import "):
                                    imports.append(line.strip())
                            methods_code = re.sub(r'import\s+[^;]+;', '', methods_code)
                            methods_code = re.sub(r'public\s+class\s+\w+\s*\{', '', methods_code)
                            if methods_code.strip().endswith('}'):
                                methods_code = methods_code.strip()[:-1].strip()

                        merged_code = self._merge_test_methods(existing_test_source, imports, methods_code)
                        
                        with open(test_file_path, "w", encoding="utf-8") as f:
                            f.write(merged_code)

                        log_msg(f"[Testing] Merged {len(uncovered)} new test methods into {class_name}Test.java")

                    # AUTO-CORRECTION LOOP: run compilation check
                    correction_count, compiled = await self._auto_correction_loop(
                        project_path=project_path,
                        file_path=file_path,
                        test_file_path=test_file_path,
                        class_name=class_name,
                        class_meta=self._get_class_meta_dict(class_meta),
                        build_tool=build_tool,
                        java_source=java_source
                    )
                    total_correction_attempts += correction_count

                    generated_count += 1
                    generated_files_list.append(test_file_path)

                except Exception as class_err:
                    log_msg(f"[Testing] Error generating/merging tests for class {class_name}: {class_err}")
                    # Continue generating tests for remaining classes, do not stop the migration
                    continue

            result["tests_generated"] = generated_count
            result["generated_files"] = generated_files_list
            result["correction_attempts"] = total_correction_attempts
            result["message"] = f"Generated/merged {generated_count} JUnit 5 test classes. Auto-correction attempts: {total_correction_attempts}."

        except Exception as e:
            result["success"] = False
            result["message"] = f"Error in test generation workflow: {e}"
            print(f"Error in TestGenerator: {e}")
            import traceback
            traceback.print_exc()

        return result

    async def _auto_correction_loop(
        self,
        project_path: str,
        file_path: str,
        test_file_path: str,
        class_name: str,
        class_meta: Dict[str, Any],
        build_tool: str,
        java_source: str
    ) -> tuple:
        """
        Runs a compilation check and execution check after generating each test class.
        If either fails, sends the errors/stacktrace back to Gemini for fixing.
        """
        correction_count = 0
        package_name = getattr(class_meta, "package_name", "") if not isinstance(class_meta, dict) else class_meta.get("package_name", "")

        for attempt in range(self.max_retries):
            # 1. Check Compilation
            compiles, compiler_errors = await self._check_compilation(project_path, test_file_path, build_tool)
            
            if not compiles:
                correction_count += 1
                print(f"Compilation failed for {class_name}Test (attempt {attempt + 1}). Errors:")
                print(compiler_errors[:500])
                
                if attempt < self.max_retries - 1:
                    try:
                        with open(test_file_path, "r", encoding="utf-8", errors="ignore") as f:
                            current_test_code = f.read()
                    except Exception:
                        break

                    fixed_code = await self.client.fix_compilation_errors(
                        production_source=java_source,
                        generated_test=current_test_code,
                        compiler_errors=compiler_errors,
                        class_meta=class_meta
                    )

                    if fixed_code:
                        cleaned_fixed = self.validator.clean_and_validate(fixed_code, class_name, class_meta)
                        if cleaned_fixed:
                            with open(test_file_path, "w", encoding="utf-8") as f:
                                f.write(cleaned_fixed)
                            print(f"Applied compilation fix for {class_name}Test.")
                            continue
                    break
                else:
                    break

            # 2. Check Execution
            passes, execution_errors = await self._run_single_test(project_path, class_name, package_name, build_tool)
            
            if passes:
                print(f"Compilation successful for {class_name}Test")
                print(f"Test {class_name}Test compiled and passed successfully!")
                return correction_count, True
                
            # A generated test that compiles but fails execution is not committed. Gemini
            # repair requests are reserved for compiler diagnostics only.
            print(f"Execution failed for {class_name}Test: {execution_errors[:500]}")
            break

        return correction_count, False

    async def _check_compilation(self, project_path: str, test_file_path: str, build_tool: str) -> tuple:
        """
        Compiles the project using Maven or Gradle to check for errors.
        Returns (compiles: bool, errors: str).
        """
        try:
            is_windows = sys.platform == "win32"
            cmd = []
            
            if build_tool == "maven":
                mvnw_cmd_path = os.path.join(project_path, "mvnw.cmd")
                mvnw_sh_path = os.path.join(project_path, "mvnw")
                if is_windows and os.path.exists(mvnw_cmd_path):
                    cmd = [".\\mvnw.cmd", "test-compile"]
                elif not is_windows and os.path.exists(mvnw_sh_path):
                    cmd = ["./mvnw", "test-compile"]
                else:
                    cmd = ["mvn", "test-compile"]
            elif build_tool == "gradle":
                gradlew_bat_path = os.path.join(project_path, "gradlew.bat")
                gradlew_sh_path = os.path.join(project_path, "gradlew")
                if is_windows and os.path.exists(gradlew_bat_path):
                    cmd = [".\\gradlew.bat", "testClasses"]
                elif not is_windows and os.path.exists(gradlew_sh_path):
                    cmd = ["./gradlew", "testClasses"]
                else:
                    cmd = ["gradle", "testClasses"]
            else:
                return True, ""

            cmd_str = " ".join(cmd)
            print(f"Running compilation check command: {cmd_str}")
            
            process = await asyncio.create_subprocess_shell(
                cmd_str,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=project_path
            )
            
            try:
                stdout_bytes, stderr_bytes = await asyncio.wait_for(process.communicate(), timeout=self.compile_timeout)
                stdout = stdout_bytes.decode('utf-8', errors='ignore')
                stderr = stderr_bytes.decode('utf-8', errors='ignore')
            except asyncio.TimeoutError:
                process.kill()
                return False, "Compilation timed out"

            if process.returncode == 0:
                return True, ""
            
            # Non-zero return code means compilation failed
            full_output = stdout + "\n" + stderr
            test_file_basename = os.path.basename(test_file_path)
            # Gemini must receive diagnostics for this generated test only. Do not leak
            # unrelated project compiler errors into a repair request.
            error_lines = [
                line for line in full_output.splitlines()
                if test_file_basename.lower() in line.lower()
            ]
            if not error_lines:
                return False, (
                    f"Compilation failed but diagnostics did not identify {test_file_basename}; "
                    "not sending unrelated source to Gemini."
                )
            return False, "\n".join(error_lines)

        except Exception as e:
            return True, f"Error during compilation check: {e}"

    async def _run_single_test(self, project_path: str, class_name: str, package_name: str, build_tool: str) -> tuple:
        """
        Executes only the generated test class to check if it passes.
        Returns (success: bool, errors_or_stacktrace: str).
        """
        try:
            is_windows = sys.platform == "win32"
            cmd = []
            
            if build_tool == "maven":
                mvnw_cmd_path = os.path.join(project_path, "mvnw.cmd")
                mvnw_sh_path = os.path.join(project_path, "mvnw")
                if is_windows and os.path.exists(mvnw_cmd_path):
                    cmd = [".\\mvnw.cmd", "test", f"-Dtest={class_name}Test", "-Dmaven.test.failure.ignore=false"]
                elif not is_windows and os.path.exists(mvnw_sh_path):
                    cmd = ["./mvnw", "test", f"-Dtest={class_name}Test", "-Dmaven.test.failure.ignore=false"]
                else:
                    cmd = ["mvn", "test", f"-Dtest={class_name}Test", "-Dmaven.test.failure.ignore=false"]
            elif build_tool == "gradle":
                gradlew_bat_path = os.path.join(project_path, "gradlew.bat")
                gradlew_sh_path = os.path.join(project_path, "gradlew")
                test_filter = f"{package_name}.{class_name}Test" if package_name else f"{class_name}Test"
                if is_windows and os.path.exists(gradlew_bat_path):
                    cmd = [".\\gradlew.bat", "test", "--tests", test_filter]
                elif not is_windows and os.path.exists(gradlew_sh_path):
                    cmd = ["./gradlew", "test", "--tests", test_filter]
                else:
                    cmd = ["gradle", "test", "--tests", test_filter]
            else:
                return True, ""

            cmd_str = " ".join(cmd)
            print(f"Running validation test command: {cmd_str}")
            
            process = await asyncio.create_subprocess_shell(
                cmd_str,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=project_path
            )
            
            try:
                stdout_bytes, stderr_bytes = await asyncio.wait_for(process.communicate(), timeout=120)
                stdout = stdout_bytes.decode('utf-8', errors='ignore')
                stderr = stderr_bytes.decode('utf-8', errors='ignore')
            except asyncio.TimeoutError:
                process.kill()
                return False, "Test execution timed out after 120 seconds."

            if process.returncode == 0:
                return True, ""
            
            # Non-zero exit code means test failed. Parse XML report for details.
            failures_str = self._parse_test_execution_failure(project_path, class_name, package_name, build_tool)
            return False, failures_str

        except Exception as e:
            return False, f"Error running validation test: {e}"

    def _parse_test_execution_failure(self, project_path: str, class_name: str, package_name: str, build_tool: str) -> str:
        """Parses the Surefire/Gradle XML test report to extract the failure message and stack trace"""
        xml_filename = f"TEST-{package_name}.{class_name}Test.xml" if package_name else f"TEST-{class_name}Test.xml"
        
        # Search recursively for the XML file matching this pattern
        xml_path = None
        for root, dirs, files in os.walk(project_path):
            dirs[:] = [d for d in dirs if d not in (".git", "node_modules", "venv", ".venv")]
            if xml_filename in files:
                xml_path = os.path.join(root, xml_filename)
                break
                
        if not xml_path or not os.path.exists(xml_path):
            # Fallback: look for any XML file matching *ClassNameTest.xml
            for root, dirs, files in os.walk(project_path):
                dirs[:] = [d for d in dirs if d not in (".git", "node_modules", "venv", ".venv")]
                for file in files:
                    if file.endswith(f"{class_name}Test.xml"):
                        xml_path = os.path.join(root, file)
                        break
                if xml_path:
                    break

        if not xml_path or not os.path.exists(xml_path):
            return "Test execution failed, but no XML test report was found."

        try:
            import xml.etree.ElementTree as ET
            tree = ET.parse(xml_path)
            root = tree.getroot()
            
            failures = []
            for testcase in root.findall(".//testcase"):
                name = testcase.get("name")
                for fail in testcase.findall("failure"):
                    msg = fail.get("message", "")
                    stack = fail.text or ""
                    failures.append(f"Method: {name} - Failure: {msg}\nStacktrace:\n{stack}")
                for err in testcase.findall("error"):
                    msg = err.get("message", "")
                    stack = err.text or ""
                    failures.append(f"Method: {name} - Error: {msg}\nStacktrace:\n{stack}")
            
            if failures:
                return "\n\n".join(failures)
            return "Test execution failed (non-zero exit code), but XML report shows no failures."
        except Exception as e:
            return f"Failed to parse test report XML: {e}"