import type React from "react";

export const styles: { [key: string]: React.CSSProperties } = {
  container: { flex: 1, display: "flex", flexDirection: "column", width: "100%", maxWidth: "100vw", margin: 0, padding: 0, background: "#f8fafc", fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif", overflow: "visible" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 40px", width: "100%", boxSizing: "border-box", background: "#fff", borderBottom: "1px solid #e2e8f0" },
  logo: { display: "flex", alignItems: "center", gap: 12 },
  stepIndicatorContainer: { background: "#fff", borderBottom: "1px solid #e2e8f0", padding: "24px 40px", width: "100%", boxSizing: "border-box", overflowX: "auto" },
  stepIndicator: { display: "flex", gap: 0, justifyContent: "center", alignItems: "flex-start", minWidth: "fit-content", flexWrap: "nowrap" },
  stepItem: { display: "flex", alignItems: "center", gap: 8, padding: "6px 12px", borderRadius: 8, transition: "all 0.2s ease", cursor: "pointer", whiteSpace: "nowrap" },
  stepCircle: { width: 44, height: 44, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18, fontWeight: 600, transition: "all 0.2s ease" },
  stepLabel: { display: "flex", flexDirection: "column" },
  main: { flex: 1, width: "100%", maxWidth: "100vw", padding: "24px 40px", boxSizing: "border-box" },
  card: { background: "#fff", borderRadius: 12, padding: "28px 32px", boxShadow: "0 1px 3px rgba(0,0,0,0.1)", marginBottom: 20, width: "100%", boxSizing: "border-box", border: "1px solid #e2e8f0" },
  stepHeader: { display: "flex", alignItems: "flex-start", gap: 16, marginBottom: 24, paddingBottom: 20, borderBottom: "1px solid #e2e8f0", flexWrap: "wrap" },
  stepIcon: { fontSize: 36 },
  timerBadge: { marginLeft: "auto", display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 4, padding: "10px 14px", borderRadius: 10, background: "#eff6ff", border: "1px solid #bfdbfe", minWidth: 110 },
  timerLabel: { fontSize: 11, fontWeight: 700, color: "#2563eb", textTransform: "uppercase", letterSpacing: "0.5px" },
  timerValue: { fontSize: 20, fontWeight: 700, color: "#1e3a8a", fontVariantNumeric: "tabular-nums" },
  title: { fontSize: 22, fontWeight: 700, marginBottom: 6, color: "#1e293b" },
  subtitle: { fontSize: 14, color: "#64748b", margin: 0, lineHeight: 1.5 },
  sectionTitle: { fontSize: 16, fontWeight: 600, color: "#1e293b", marginBottom: 14, marginTop: 20, display: "flex", alignItems: "center", gap: 8 },
  field: { marginBottom: 20, width: "100%", boxSizing: "border-box" },
  label: { fontWeight: 600, fontSize: 14, marginBottom: 8, display: "block", color: "#374151" },
  input: { width: "100%", padding: "12px 14px", fontSize: 14, borderRadius: 8, border: "1px solid #d1d5db", boxSizing: "border-box", transition: "all 0.2s ease", backgroundColor: "#fff" },
  select: { width: "100%", padding: "12px 14px", fontSize: 14, borderRadius: 8, border: "1px solid #d1d5db", backgroundColor: "#fff", transition: "all 0.2s ease", cursor: "pointer" },
  helpText: { fontSize: 13, color: "#64748b", marginTop: 6, lineHeight: 1.4 },
  infoButtonContainer: { position: "relative", display: "inline-block", zIndex: 100 },
  infoButton: { width: 22, height: 22, borderRadius: "50%", background: "#e5e7eb", border: "none", cursor: "pointer", fontSize: 12, color: "#6b7280", display: "inline-flex", alignItems: "center", justifyContent: "center", transition: "all 0.2s ease", padding: 0, fontWeight: 600 },
  tooltip: { display: "none", position: "absolute", bottom: "calc(100% + 10px)", left: 0, width: 280, background: "#1e293b", color: "#f1f5f9", padding: "14px", borderRadius: 8, fontSize: 13, zIndex: 1001, boxShadow: "0 10px 25px rgba(0,0,0,0.2)" },
  link: { color: "#2563eb", textDecoration: "none", fontWeight: 500 },
  infoBox: { background: "#eff6ff", border: "1px solid #bfdbfe", borderRadius: 8, padding: 16, marginBottom: 20, fontSize: 14, color: "#1e40af", width: "100%", boxSizing: "border-box", lineHeight: 1.5 },
  warningBox: { background: "#fffbeb", border: "1px solid #fcd34d", borderRadius: 8, padding: 16, marginBottom: 20, width: "100%", boxSizing: "border-box" },
  warningTitle: { fontWeight: 600, marginBottom: 10, color: "#78350f", fontSize: 14 },
  warningList: { margin: 0, paddingLeft: 18, fontSize: 14, color: "#92400e", lineHeight: 1.6 },
  errorBanner: { background: "#fef2f2", border: "1px solid #fca5a5", borderRadius: 8, padding: "12px 16px", marginBottom: 20, display: "flex", justifyContent: "space-between", alignItems: "center", color: "#991b1b", width: "100%", boxSizing: "border-box" },
  errorClose: { background: "none", border: "none", fontSize: 18, cursor: "pointer", color: "#dc2626" },
  errorBox: { background: "#fef2f2", border: "1px solid #fca5a5", borderRadius: 8, padding: "14px 16px", marginBottom: 20, color: "#991b1b", width: "100%", boxSizing: "border-box" },
  btnRow: { display: "flex", gap: 12, marginTop: 24, justifyContent: "flex-end" },
  primaryBtn: { background: "#2563eb", color: "#fff", border: "none", borderRadius: 8, padding: "12px 24px", fontWeight: 600, cursor: "pointer", fontSize: 14, transition: "all 0.2s ease" },
  secondaryBtn: { background: "#fff", color: "#374151", border: "1px solid #d1d5db", borderRadius: 8, padding: "12px 24px", fontWeight: 500, cursor: "pointer", fontSize: 14, transition: "all 0.2s ease" },
  row: { display: "flex", gap: 20 },
  loadingBox: { display: "flex", alignItems: "center", justifyContent: "center", gap: 12, padding: 40, color: "#2563eb", fontWeight: 500, fontSize: 15 },
  spinner: { width: 24, height: 24, border: "3px solid #e5e7eb", borderTop: "3px solid #2563eb", borderRadius: "50%", animation: "spin 0.8s linear infinite" },
  repoList: { display: "flex", flexDirection: "column", gap: 8, maxHeight: 300, overflowY: "auto", paddingRight: 6 },
  repoItem: { display: "flex", alignItems: "center", gap: 12, padding: "14px 16px", border: "1px solid #e2e8f0", borderRadius: 8, cursor: "pointer", transition: "all 0.2s ease", backgroundColor: "#fff" },
  repoIcon: { fontSize: 20 },
  repoInfo: { flex: 1 },
  repoName: { fontWeight: 600, fontSize: 14, color: "#1e293b" },
  repoPath: { fontSize: 12, color: "#64748b", marginTop: 2 },
  repoLanguage: { fontSize: 11, padding: "4px 10px", background: "#eff6ff", borderRadius: 12, color: "#2563eb", fontWeight: 500 },
  arrow: { fontSize: 16, color: "#2563eb" },
  emptyText: { textAlign: "center", color: "#64748b", padding: 40, fontSize: 14 },
  selectedRepoBox: { display: "flex", alignItems: "center", gap: 12, padding: "12px 16px", background: "#eff6ff", borderRadius: 8, marginBottom: 20, border: "1px solid #bfdbfe" },
  changeBtn: { marginLeft: "auto", background: "none", border: "none", color: "#2563eb", cursor: "pointer", fontSize: 13, fontWeight: 600 },
  riskBadge: { display: "inline-block", padding: "8px 16px", borderRadius: 16, fontSize: 13, fontWeight: 600, marginBottom: 14 },
  assessmentGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 16, marginBottom: 20 },
  assessmentItem: { background: "#fff", padding: 18, borderRadius: 10, textAlign: "center", border: "1px solid #e2e8f0" },
  assessmentLabel: { fontSize: 11, color: "#64748b", marginBottom: 8, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.5px" },
  assessmentValue: { fontSize: 20, fontWeight: 700, color: "#1e293b" },
  structureBox: { background: "#f8fafc", padding: 18, borderRadius: 10, marginBottom: 20, border: "1px solid #e2e8f0" },
  structureTitle: { fontSize: 14, fontWeight: 600, marginBottom: 12, color: "#1e293b" },
  structureGrid: { display: "flex", gap: 14, flexWrap: "wrap" },
  structureFound: { color: "#059669", fontWeight: 600 },
  structureMissing: { color: "#9ca3af", fontWeight: 500 },
  dependenciesBox: { marginBottom: 20 },
  dependenciesList: { background: "#fff", borderRadius: 10, padding: 14, border: "1px solid #e2e8f0" },
  dependencyItem: { display: "flex", justifyContent: "space-between", padding: "10px 0", borderBottom: "1px solid #f1f5f9", fontSize: 13 },
  dependencyVersion: { color: "#2563eb", fontFamily: "'JetBrains Mono', monospace", fontWeight: 500 },
  moreItems: { textAlign: "center", color: "#2563eb", fontSize: 12, paddingTop: 10, fontWeight: 500 },
  radioGroup: { display: "flex", flexDirection: "column", gap: 10 },
  radioLabel: { display: "flex", alignItems: "flex-start", gap: 12, padding: 16, border: "1px solid #e2e8f0", borderRadius: 10, cursor: "pointer", transition: "all 0.2s ease", backgroundColor: "#fff" },
  radio: { marginTop: 4, accentColor: "#2563eb" },
  checkbox: { width: 18, height: 18, accentColor: "#2563eb", cursor: "pointer" },
  frameworkGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 14 },
  frameworkItem: { display: "flex", alignItems: "center", gap: 12, padding: 16, border: "1px solid #e2e8f0", borderRadius: 10, cursor: "pointer", background: "#fff", transition: "all 0.2s ease" },
  detectedBadge: { marginLeft: "auto", fontSize: 11, padding: "4px 10px", background: "#059669", color: "#fff", borderRadius: 12, fontWeight: 600 },
  conversionGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14 },
  conversionItem: { display: "flex", alignItems: "flex-start", gap: 14, padding: 18, border: "1px solid #e2e8f0", borderRadius: 10, cursor: "pointer", position: "relative", transition: "all 0.2s ease", background: "#fff" },
  conversionIcon: { fontSize: 24 },
  checkMark: { position: "absolute", top: 10, right: 10, color: "#059669", fontWeight: 700, fontSize: 18 },
  optionsGrid: { display: "flex", flexDirection: "column", gap: 14 },
  optionItem: { display: "flex", alignItems: "flex-start", gap: 14, padding: 18, border: "1px solid #e2e8f0", borderRadius: 10, cursor: "pointer", background: "#fff", transition: "all 0.2s ease" },
  progressSection: { marginBottom: 24 },
  progressHeader: { display: "flex", justifyContent: "space-between", marginBottom: 10, fontSize: 14, fontWeight: 600, color: "#1e293b" },
  progressBar: { width: "100%", height: 10, background: "#e5e7eb", borderRadius: 6, overflow: "hidden" },
  progressFill: { height: "100%", background: "#2563eb", borderRadius: 6, transition: "width 0.4s ease" },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 16, marginBottom: 24 },
  statBox: { background: "#fff", padding: 20, borderRadius: 10, textAlign: "center", border: "1px solid #e2e8f0" },
  statValue: { fontSize: 28, fontWeight: 700, color: "#2563eb" },
  statLabel: { fontSize: 12, color: "#64748b", marginTop: 8, fontWeight: 600, textTransform: "uppercase" },
  successBox: { background: "#dcfce7", border: "1px solid #86efac", borderRadius: 12, padding: 28, textAlign: "center", marginBottom: 24 },
  successTitle: { fontSize: 20, fontWeight: 700, color: "#166534", marginBottom: 12 },
  repoLink: { display: "inline-block", color: "#2563eb", fontWeight: 600, textDecoration: "none", fontSize: 14, padding: "10px 20px", background: "#eff6ff", borderRadius: 8 },
  connectionModes: { display: "flex", gap: 14, marginBottom: 20 },
  modeButton: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 8, padding: 20, border: "1px solid #e2e8f0", borderRadius: 10, background: "#fff", cursor: "pointer", transition: "all 0.2s ease", fontWeight: 500 },
  modeButtonActive: { border: "1px solid #2563eb", background: "#eff6ff" },
  modeIcon: { fontSize: 28 },
  modeTitle: { fontWeight: 600, fontSize: 14 },
  modeDesc: { fontSize: 12, color: "#64748b", textAlign: "center", lineHeight: 1.4 },
  fileList: { display: "flex", flexDirection: "column", gap: 8, maxHeight: 380, overflowY: "auto", border: "1px solid #e2e8f0", borderRadius: 10, padding: 14, background: "#f8fafc" },
  breadcrumb: { display: "flex", alignItems: "center", gap: 12, marginBottom: 14, padding: "10px 14px", background: "#eff6ff", borderRadius: 8, border: "1px solid #bfdbfe" },
  backBtn: { background: "none", border: "none", color: "#2563eb", cursor: "pointer", fontSize: 14, fontWeight: 600 },
  fileItem: { display: "flex", alignItems: "center", gap: 12, padding: "14px 16px", border: "1px solid #e2e8f0", borderRadius: 8, cursor: "pointer", transition: "all 0.2s ease", backgroundColor: "#fff" },
  fileIcon: { fontSize: 20 },
  fileInfo: { flex: 1 },
  fileName: { fontWeight: 600, fontSize: 14, color: "#1e293b" },
  filePath: { fontSize: 12, color: "#64748b", marginTop: 2 },
  fileSize: { fontSize: 11, color: "#94a3b8", fontWeight: 500, padding: "3px 8px", backgroundColor: "#f1f5f9", borderRadius: 6 },
  discoveryContent: { display: "flex", flexDirection: "column", gap: 14 },
  discoveryItem: { display: "flex", alignItems: "center", gap: 14, padding: 18, background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  discoveryIcon: { fontSize: 26 },
  discoveryTitle: { fontSize: 15, fontWeight: 600, color: "#1e293b", marginBottom: 2 },
  discoveryDesc: { fontSize: 13, color: "#64748b" },
  detectedConfigCard: { background: "linear-gradient(135deg, #eff6ff 0%, #f8fafc 100%)", border: "1px solid #bfdbfe", borderRadius: 12, padding: 20, marginTop: 18, marginBottom: 20 },
  detectedConfigHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, marginBottom: 14 },
  detectedConfigTitle: { fontSize: 16, fontWeight: 700, color: "#1e3a8a", marginBottom: 4 },
  detectedConfigSubtitle: { fontSize: 13, color: "#475569", lineHeight: 1.5 },
  detectedConfigActions: { display: "flex", flexWrap: "wrap", gap: 12, marginBottom: 12 },
  detectedConfigChip: { padding: "10px 14px", borderRadius: 999, border: "1px solid #93c5fd", background: "#fff", color: "#1e3a8a", fontSize: 13, fontWeight: 600, cursor: "default" },
  detectedConfigActionBtn: { padding: "10px 16px", borderRadius: 999, border: "1px solid #2563eb", background: "#2563eb", color: "#fff", fontSize: 13, fontWeight: 700, cursor: "pointer", transition: "all 0.2s ease" },
  detectedConfigActionBtnActive: { background: "#1d4ed8", borderColor: "#1d4ed8", boxShadow: "0 0 0 3px rgba(37, 99, 235, 0.15)" },
  detectedConfigNote: { fontSize: 12, color: "#475569", lineHeight: 1.5 },
  reportContainer: { display: "flex", flexDirection: "column", gap: 20 },
  reportSection: { background: "#fff", borderRadius: 12, padding: 22, border: "1px solid #e2e8f0" },
  reportTitle: { fontSize: 17, fontWeight: 700, color: "#1e293b", marginBottom: 18, paddingBottom: 12, borderBottom: "1px solid #e2e8f0", display: "flex", alignItems: "center", gap: 10 },
  reportGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 14 },
  reportItem: { display: "flex", flexDirection: "column", gap: 6 },
  reportLabel: { fontSize: 11, color: "#64748b", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.5px" },
  reportValue: { fontSize: 14, color: "#1e293b", fontWeight: 600 },
  testResults: { display: "flex", flexDirection: "column", gap: 10 },
  testItem: { display: "flex", justifyContent: "space-between", padding: "14px 18px", background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  sonarqubeResults: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 16 },
  qualityItem: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 18px", background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  logsContainer: { background: "#1e293b", color: "#10b981", fontFamily: "'JetBrains Mono', 'Fira Code', monospace", padding: 18, borderRadius: 10, maxHeight: 300, overflowY: "auto", fontSize: 12, lineHeight: 1.6, border: "1px solid #334155" },
  logEntry: { marginBottom: 6, padding: "3px 0", borderBottom: "1px solid rgba(255,255,255,0.05)" },
  issuesContainer: { display: "flex", flexDirection: "column", gap: 12 },
  issueItem: { padding: 18, background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  issueHeader: { display: "flex", alignItems: "center", gap: 12, marginBottom: 10 },
  issueSeverity: { padding: "6px 12px", borderRadius: 12, fontSize: 11, fontWeight: 600, color: "#fff", textTransform: "uppercase" },
  issueCategory: { fontSize: 12, color: "#64748b", fontWeight: 600, textTransform: "uppercase" },
  issueStatus: { fontSize: 12, color: "#059669", fontWeight: 600, marginLeft: "auto" },
  issueMessage: { fontSize: 14, color: "#1e293b", marginBottom: 8, fontWeight: 500, lineHeight: 1.4 },
  issueFile: { fontSize: 12, color: "#2563eb", fontFamily: "'JetBrains Mono', monospace", backgroundColor: "#eff6ff", padding: "6px 12px", borderRadius: 6, display: "inline-block" },
  noIssues: { textAlign: "center", color: "#64748b", padding: 28, fontStyle: "italic", fontSize: 14 },
  noFilesMsg: { textAlign: "center", color: "#64748b", padding: 28, fontStyle: "italic", background: "#f8fafc", borderRadius: 10, border: "1px dashed #e2e8f0" },
  noLogs: { textAlign: "center", color: "#64748b", padding: 28, fontStyle: "italic" },

  // Animation styles
  animationContainer: { padding: 24, background: "#f8fafc", borderRadius: 12, marginTop: 20, border: "1px solid #e2e8f0" },
  migrationAnimation: { maxWidth: 600, margin: "0 auto" },
  animationHeader: { textAlign: "center", marginBottom: 32 },
  migratingText: { fontSize: 24, fontWeight: 700, color: "#1e293b", marginBottom: 10 },
  versionTransition: { fontSize: 14, color: "#fff", padding: "10px 20px", background: "#2563eb", borderRadius: 20, display: "inline-block", fontWeight: 600 },
  animationSteps: { display: "flex", flexDirection: "column", gap: 14, marginBottom: 28 },
  animationStep: { display: "flex", alignItems: "center", gap: 14, padding: 18, background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  stepIconAnimated: { fontSize: 22, minWidth: 22 },
  stepText: { flex: 1, fontSize: 14, fontWeight: 500, color: "#1e293b" },
  checkMarkAnimated: { fontSize: 18, color: "#059669" },
  animatedProgressSection: { marginBottom: 24 },
  animatedProgressHeader: { display: "flex", justifyContent: "space-between", marginBottom: 12, fontSize: 14, fontWeight: 600, color: "#1e293b" },
  animatedProgressBar: { width: "100%", height: 12, background: "#e5e7eb", borderRadius: 8, overflow: "hidden" },
  animatedProgressFill: { height: "100%", borderRadius: 8, transition: "width 0.4s ease", background: "#2563eb" },
  statusMessages: { textAlign: "center" },
  currentStatus: { fontSize: 16, fontWeight: 600, color: "#1e293b", marginBottom: 10 },
  recentLog: { fontSize: 13, color: "#64748b", fontFamily: "'JetBrains Mono', monospace", background: "#f8fafc", padding: "12px 16px", borderRadius: 8, border: "1px solid #e2e8f0" },

  // Report styles
  changesGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 14 },
  changeItem: { display: "flex", alignItems: "center", gap: 14, padding: 18, background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  changeIcon: { fontSize: 26 },
  changeTitle: { fontSize: 14, fontWeight: 600, color: "#1e293b", marginBottom: 4 },
  changeValue: { fontSize: 13, color: "#64748b" },
  dependenciesReport: { display: "flex", flexDirection: "column", gap: 10 },
  dependencyReportItem: { display: "grid", gridTemplateColumns: "1fr 200px 140px", gap: 14, alignItems: "center", padding: "14px 18px", background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  dependencyName: { fontSize: 14, fontWeight: 600, color: "#1e293b", fontFamily: "'JetBrains Mono', monospace", wordBreak: "break-word" },
  dependencyChange: { fontSize: 13, color: "#64748b", textAlign: "center" },
  dependencyStatus: { padding: "6px 12px", borderRadius: 12, fontSize: 11, fontWeight: 600, textTransform: "uppercase", textAlign: "center" },
  noData: { textAlign: "center", color: "#64748b", padding: 28, fontStyle: "italic" },
  errorsSummary: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 14 },
  errorStat: { textAlign: "center", padding: 18, background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  errorCount: { display: "block", fontSize: 26, fontWeight: 700, color: "#1e293b", marginBottom: 6 },
  errorLabel: { fontSize: 12, color: "#64748b", fontWeight: 600, textTransform: "uppercase" },
  businessLogicGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 14 },
  businessItem: { display: "flex", alignItems: "flex-start", gap: 14, padding: 18, background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  businessIcon: { fontSize: 26, marginTop: 2 },
  businessTitle: { fontSize: 14, fontWeight: 600, color: "#1e293b", marginBottom: 6 },
  businessDesc: { fontSize: 13, color: "#64748b", lineHeight: 1.5 },
  sonarqubeGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 20, marginBottom: 20 },
  sonarqubeItem: { textAlign: "center" },
  qualityGate: { marginBottom: 18 },
  gateStatus: { display: "inline-block", padding: "12px 24px", borderRadius: 20, color: "#fff", fontSize: 14, fontWeight: 700, textTransform: "uppercase" },
  gateLabel: { display: "block", fontSize: 12, color: "#64748b", marginTop: 10, fontWeight: 600 },
  coverageMeter: { position: "relative" },
  coverageCircle: { width: 110, height: 110, borderRadius: "50%", background: "#eff6ff", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", margin: "0 auto", border: "3px solid #2563eb" },
  coveragePercent: { fontSize: 26, fontWeight: 700, color: "#2563eb" },
  coverageLabel: { fontSize: 11, color: "#64748b", fontWeight: 600, marginTop: 2 },
  qualityMetrics: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 14 },
  metricItem: { textAlign: "center", padding: 14, background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  metricValue: { display: "block", fontSize: 22, fontWeight: 700, marginBottom: 6, color: "#1e293b" },
  metricLabel: { fontSize: 11, color: "#64748b", fontWeight: 600, textTransform: "uppercase" },
  testReportGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 14, marginBottom: 18 },
  testMetric: { textAlign: "center", padding: 18, background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  testValue: { display: "block", fontSize: 24, fontWeight: 700, color: "#2563eb", marginBottom: 6 },
  testLabel: { fontSize: 12, color: "#64748b", fontWeight: 600, textTransform: "uppercase" },
  testStatus: { display: "flex", alignItems: "center", gap: 10, padding: 14, background: "#dcfce7", borderRadius: 10, border: "1px solid #86efac" },
  testStatusIcon: { fontSize: 18 },
  jmeterGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14 },
  jmeterItem: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 20px", background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  jmeterLabel: { fontSize: 14, color: "#64748b" },
  jmeterValue: { fontSize: 16, fontWeight: 700, color: "#1e293b" },
};
