import type React from "react";

const glassSurface: React.CSSProperties = {
  background: "var(--theme-card-bg, linear-gradient(135deg, rgba(255, 255, 255, 0.78) 0%, rgba(248, 250, 252, 0.6) 100%))",
  border: "1px solid var(--theme-card-border, rgba(255, 255, 255, 0.38))",
  boxShadow: "var(--theme-card-shadow, 0 14px 34px rgba(15, 23, 42, 0.1), inset 0 1px 0 rgba(255, 255, 255, 0.64))",
  backdropFilter: "blur(14px) saturate(135%)",
  WebkitBackdropFilter: "blur(14px) saturate(135%)",
};

const glassField: React.CSSProperties = {
  backgroundColor: "var(--theme-input-bg, rgba(255, 255, 255, 0.72))",
  border: "1px solid var(--theme-input-border, rgba(209, 213, 219, 0.72))",
  backdropFilter: "blur(12px) saturate(135%)",
  WebkitBackdropFilter: "blur(12px) saturate(135%)",
};

export const styles: { [key: string]: React.CSSProperties } = {
  container: { flex: 1, display: "flex", flexDirection: "column", alignItems: "stretch", width: "100%", maxWidth: "100vw", margin: 0, padding: 0, background: "transparent", fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif", overflow: "visible" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 40px", width: "100%", boxSizing: "border-box", background: "var(--theme-header-bg, rgba(255, 255, 255, 0.76))", borderBottom: "1px solid var(--theme-border, rgba(255, 255, 255, 0.38))", boxShadow: "0 12px 32px rgba(15, 23, 42, 0.08)", backdropFilter: "blur(16px) saturate(140%)", WebkitBackdropFilter: "blur(16px) saturate(140%)" },
  logo: { display: "flex", alignItems: "center", gap: 12 },
  stepIndicatorContainer: { background: "var(--theme-sidebar-bg, rgba(59, 36, 22, 0.62))", borderBottom: "1px solid rgba(251, 191, 36, 0.16)", padding: "10px 0", width: "100%", boxSizing: "border-box", overflowX: "auto", overflowY: "hidden" },
  stepIndicator: { display: "flex", gap: 0, justifyContent: "center", alignItems: "flex-start", minWidth: "fit-content", flexWrap: "nowrap" },
  stepItem: { display: "flex", alignItems: "center", gap: 8, padding: "6px 12px", borderRadius: 8, transition: "all 0.2s ease", cursor: "pointer", whiteSpace: "nowrap" },
  stepCircle: { width: 44, height: 44, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18, fontWeight: 600, transition: "all 0.2s ease" },
  stepLabel: { display: "flex", flexDirection: "column" },
  main: { flex: 1, minWidth: 0, width: "100%", maxWidth: "100vw", padding: "24px 32px", boxSizing: "border-box" },
  card: { ...glassSurface, borderRadius: 12, padding: "28px 32px", marginBottom: 20, width: "100%", boxSizing: "border-box", backdropFilter: "blur(18px) saturate(140%)", WebkitBackdropFilter: "blur(18px) saturate(140%)" },
  stepHeader: { display: "flex", alignItems: "flex-start", gap: 16, marginBottom: 24, paddingBottom: 20, borderBottom: "1px solid var(--theme-border, #e2e8f0)", flexWrap: "wrap" },
  stepIcon: { fontSize: 36 },
  timerBadge: { marginLeft: "auto", display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 4, padding: "10px 14px", borderRadius: 10, background: "var(--theme-tint, rgba(239, 246, 255, 0.72))", border: "1px solid var(--theme-border-strong, rgba(147, 197, 253, 0.58))", minWidth: 110, backdropFilter: "blur(12px) saturate(135%)", WebkitBackdropFilter: "blur(12px) saturate(135%)" },
  timerLabel: { fontSize: 11, fontWeight: 700, color: "var(--theme-accent, #2563eb)", textTransform: "uppercase", letterSpacing: "0.5px" },
  timerValue: { fontSize: 20, fontWeight: 700, color: "var(--theme-text-strong, #1e3a8a)", fontVariantNumeric: "tabular-nums" },
  title: { fontSize: 22, fontWeight: 700, marginBottom: 6, color: "var(--theme-text-strong, #1e293b)" },
  subtitle: { fontSize: 14, color: "var(--theme-muted, #64748b)", margin: 0, lineHeight: 1.5 },
  sectionTitle: { fontSize: 16, fontWeight: 600, color: "var(--theme-text-strong, #1e293b)", marginBottom: 14, marginTop: 20, display: "flex", alignItems: "center", gap: 8 },
  field: { marginBottom: 20, width: "100%", boxSizing: "border-box" },
  label: { fontWeight: 600, fontSize: 14, marginBottom: 8, display: "block", color: "var(--theme-text, #374151)" },
  input: { ...glassField, width: "100%", padding: "12px 14px", fontSize: 14, borderRadius: 8, boxSizing: "border-box", transition: "all 0.2s ease" },
  select: { ...glassField, width: "100%", padding: "12px 14px", fontSize: 14, borderRadius: 8, transition: "all 0.2s ease", cursor: "pointer" },
  helpText: { fontSize: 13, color: "#64748b", marginTop: 6, lineHeight: 1.4 },
  infoButtonContainer: { position: "relative", display: "inline-block", zIndex: 100 },
  infoButton: { width: 22, height: 22, borderRadius: "50%", background: "#e5e7eb", border: "none", cursor: "pointer", fontSize: 12, color: "#6b7280", display: "inline-flex", alignItems: "center", justifyContent: "center", transition: "all 0.2s ease", padding: 0, fontWeight: 600 },
  tooltip: { display: "none", position: "absolute", bottom: "calc(100% + 10px)", left: 0, width: 280, background: "#1e293b", color: "#f1f5f9", padding: "14px", borderRadius: 8, fontSize: 13, zIndex: 1001, boxShadow: "0 10px 25px rgba(0,0,0,0.2)" },
  link: { color: "var(--theme-accent, #2563eb)", textDecoration: "none", fontWeight: 500 },
  infoBox: { background: "rgba(239, 246, 255, 0.72)", border: "1px solid rgba(147, 197, 253, 0.58)", borderRadius: 8, padding: 16, marginBottom: 20, fontSize: 14, color: "#1e40af", width: "100%", boxSizing: "border-box", lineHeight: 1.5, backdropFilter: "blur(12px) saturate(135%)", WebkitBackdropFilter: "blur(12px) saturate(135%)" },
  warningBox: { background: "rgba(255, 251, 235, 0.78)", border: "1px solid rgba(252, 211, 77, 0.68)", borderRadius: 8, padding: 16, marginBottom: 20, width: "100%", boxSizing: "border-box", backdropFilter: "blur(12px) saturate(135%)", WebkitBackdropFilter: "blur(12px) saturate(135%)" },
  warningTitle: { fontWeight: 600, marginBottom: 10, color: "#78350f", fontSize: 14 },
  warningList: { margin: 0, paddingLeft: 18, fontSize: 14, color: "#92400e", lineHeight: 1.6 },
  errorBanner: { background: "rgba(254, 242, 242, 0.78)", border: "1px solid rgba(252, 165, 165, 0.68)", borderRadius: 8, padding: "12px 16px", marginBottom: 20, display: "flex", justifyContent: "space-between", alignItems: "center", color: "#991b1b", width: "100%", boxSizing: "border-box", backdropFilter: "blur(12px) saturate(135%)", WebkitBackdropFilter: "blur(12px) saturate(135%)" },
  errorClose: { background: "none", border: "none", fontSize: 18, cursor: "pointer", color: "#dc2626" },
  errorBox: { background: "rgba(254, 242, 242, 0.78)", border: "1px solid rgba(252, 165, 165, 0.68)", borderRadius: 8, padding: "14px 16px", marginBottom: 20, color: "#991b1b", width: "100%", boxSizing: "border-box", backdropFilter: "blur(12px) saturate(135%)", WebkitBackdropFilter: "blur(12px) saturate(135%)" },
  btnRow: { display: "flex", gap: 12, marginTop: 24, justifyContent: "flex-end" },
  primaryBtn: { background: "linear-gradient(135deg, var(--theme-accent, #2563eb), var(--theme-accent-2, #06b6d4))", color: "#fff", border: "none", borderRadius: 8, padding: "12px 24px", fontWeight: 600, cursor: "pointer", fontSize: 14, transition: "all 0.2s ease" },
  secondaryBtn: { background: "var(--theme-input-bg, rgba(255, 255, 255, 0.72))", color: "var(--theme-text, #374151)", border: "1px solid var(--theme-input-border, rgba(209, 213, 219, 0.72))", borderRadius: 8, padding: "12px 24px", fontWeight: 500, cursor: "pointer", fontSize: 14, transition: "all 0.2s ease", backdropFilter: "blur(12px) saturate(135%)", WebkitBackdropFilter: "blur(12px) saturate(135%)" },
  row: { display: "flex", gap: 20 },
  loadingBox: { display: "flex", alignItems: "center", justifyContent: "center", gap: 12, padding: 40, color: "var(--theme-accent, #2563eb)", fontWeight: 500, fontSize: 15 },
  spinner: { width: 24, height: 24, border: "3px solid #e5e7eb", borderTop: "3px solid var(--theme-accent, #2563eb)", borderRadius: "50%", animation: "spin 0.8s linear infinite" },
  repoList: { display: "flex", flexDirection: "column", gap: 8, maxHeight: 300, overflowY: "auto", paddingRight: 6 },
  repoItem: { ...glassSurface, display: "flex", alignItems: "center", gap: 12, padding: "14px 16px", borderRadius: 8, cursor: "pointer", transition: "all 0.2s ease" },
  repoIcon: { fontSize: 20 },
  repoInfo: { flex: 1 },
  repoName: { fontWeight: 600, fontSize: 14, color: "#1e293b" },
  repoPath: { fontSize: 12, color: "#64748b", marginTop: 2 },
  repoLanguage: { fontSize: 11, padding: "4px 10px", background: "rgba(var(--theme-accent-rgb, 37, 99, 235), 0.1)", borderRadius: 12, color: "var(--theme-accent, #2563eb)", fontWeight: 500 },
  arrow: { fontSize: 16, color: "var(--theme-accent, #2563eb)" },
  emptyText: { textAlign: "center", color: "#64748b", padding: 40, fontSize: 14 },
  selectedRepoBox: { display: "flex", alignItems: "center", gap: 12, padding: "12px 16px", background: "rgba(239, 246, 255, 0.72)", borderRadius: 8, marginBottom: 20, border: "1px solid rgba(147, 197, 253, 0.58)", backdropFilter: "blur(12px) saturate(135%)", WebkitBackdropFilter: "blur(12px) saturate(135%)" },
  changeBtn: { marginLeft: "auto", background: "none", border: "none", color: "var(--theme-accent, #2563eb)", cursor: "pointer", fontSize: 13, fontWeight: 600 },
  riskBadge: { display: "inline-block", padding: "8px 16px", borderRadius: 16, fontSize: 13, fontWeight: 600, marginBottom: 14 },
  assessmentGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 16, marginBottom: 20 },
  assessmentItem: { ...glassSurface, padding: 18, borderRadius: 10, textAlign: "center" },
  assessmentLabel: { fontSize: 11, color: "#64748b", marginBottom: 8, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.5px" },
  assessmentValue: { fontSize: 20, fontWeight: 700, color: "#1e293b" },
  structureBox: { ...glassSurface, padding: 18, borderRadius: 10, marginBottom: 20 },
  structureTitle: { fontSize: 14, fontWeight: 600, marginBottom: 12, color: "#1e293b" },
  structureGrid: { display: "flex", gap: 14, flexWrap: "wrap" },
  structureFound: { color: "#059669", fontWeight: 600 },
  structureMissing: { color: "#9ca3af", fontWeight: 500 },
  dependenciesBox: { marginBottom: 20 },
  dependenciesList: { ...glassSurface, borderRadius: 10, padding: 14 },
  dependencyItem: { display: "flex", justifyContent: "space-between", gap: 16, padding: "10px 0", borderBottom: "1px solid rgba(226, 232, 240, 0.9)", fontSize: 13, color: "#1e293b", fontWeight: 600 },
  dependencyVersion: { color: "var(--theme-accent, #1d4ed8)", fontFamily: "'JetBrains Mono', monospace", fontWeight: 700 },
  moreItems: { textAlign: "center", color: "var(--theme-accent, #2563eb)", fontSize: 12, paddingTop: 10, fontWeight: 500 },
  radioGroup: { display: "flex", flexDirection: "column", gap: 10 },
  radioLabel: { ...glassSurface, display: "flex", alignItems: "flex-start", gap: 12, padding: 16, borderRadius: 10, cursor: "pointer", transition: "all 0.2s ease" },
  radio: { marginTop: 4, accentColor: "#2563eb" },
  checkbox: { width: 18, height: 18, accentColor: "#2563eb", cursor: "pointer" },
  frameworkGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 14 },
  frameworkItem: { ...glassSurface, display: "flex", alignItems: "center", gap: 12, padding: 16, borderRadius: 10, cursor: "pointer", transition: "all 0.2s ease" },
  detectedBadge: { marginLeft: "auto", fontSize: 11, padding: "4px 10px", background: "#059669", color: "#fff", borderRadius: 12, fontWeight: 600 },
  conversionGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14 },
  conversionItem: { ...glassSurface, display: "flex", alignItems: "flex-start", gap: 14, padding: 18, borderRadius: 10, cursor: "pointer", position: "relative", transition: "all 0.2s ease" },
  conversionIcon: { fontSize: 24 },
  checkMark: { position: "absolute", top: 10, right: 10, color: "#059669", fontWeight: 700, fontSize: 18 },
  optionsGrid: { display: "flex", flexDirection: "column", gap: 14 },
  optionItem: { ...glassSurface, display: "flex", alignItems: "flex-start", gap: 14, padding: 18, borderRadius: 10, cursor: "pointer", transition: "all 0.2s ease" },
  progressSection: { marginBottom: 24 },
  progressHeader: { display: "flex", justifyContent: "space-between", marginBottom: 10, fontSize: 14, fontWeight: 600, color: "#1e293b" },
  progressBar: { width: "100%", height: 10, background: "#e5e7eb", borderRadius: 6, overflow: "hidden" },
  progressFill: { height: "100%", background: "linear-gradient(135deg, var(--theme-accent, #2563eb), var(--theme-accent-2, #06b6d4))", borderRadius: 6, transition: "width 0.4s ease" },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 16, marginBottom: 24 },
  statBox: { ...glassSurface, padding: 20, borderRadius: 10, textAlign: "center" },
  statValue: { fontSize: 28, fontWeight: 700, color: "var(--theme-accent, #2563eb)" },
  statLabel: { fontSize: 12, color: "#64748b", marginTop: 8, fontWeight: 600, textTransform: "uppercase" },
  successBox: { background: "#dcfce7", border: "1px solid #86efac", borderRadius: 12, padding: 28, textAlign: "center", marginBottom: 24 },
  successTitle: { fontSize: 20, fontWeight: 700, color: "#166534", marginBottom: 12 },
  repoLink: { display: "inline-block", color: "var(--theme-accent, #2563eb)", fontWeight: 600, textDecoration: "none", fontSize: 14, padding: "10px 20px", background: "rgba(var(--theme-accent-rgb, 37, 99, 235), 0.1)", borderRadius: 8 },
  connectionModes: { display: "flex", gap: 14, marginBottom: 20 },
  modeButton: { ...glassSurface, flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 8, padding: 20, borderRadius: 10, cursor: "pointer", transition: "all 0.2s ease", fontWeight: 500 },
  modeButtonActive: { border: "1px solid #2563eb", background: "rgba(239, 246, 255, 0.78)" },
  modeIcon: { fontSize: 28 },
  modeTitle: { fontWeight: 600, fontSize: 14 },
  modeDesc: { fontSize: 12, color: "#64748b", textAlign: "center", lineHeight: 1.4 },
  fileList: { ...glassSurface, display: "flex", flexDirection: "column", gap: 8, maxHeight: 380, overflowY: "auto", borderRadius: 10, padding: 14 },
  breadcrumb: { display: "flex", alignItems: "center", gap: 12, marginBottom: 14, padding: "10px 14px", background: "rgba(239, 246, 255, 0.72)", borderRadius: 8, border: "1px solid rgba(147, 197, 253, 0.58)", backdropFilter: "blur(12px) saturate(135%)", WebkitBackdropFilter: "blur(12px) saturate(135%)" },
  backBtn: { background: "none", border: "none", color: "#2563eb", cursor: "pointer", fontSize: 14, fontWeight: 600 },
  fileItem: { ...glassSurface, display: "flex", alignItems: "center", gap: 12, padding: "14px 16px", borderRadius: 8, cursor: "pointer", transition: "all 0.2s ease" },
  fileIcon: { fontSize: 20 },
  fileInfo: { flex: 1 },
  fileName: { fontWeight: 600, fontSize: 14, color: "#1e293b" },
  filePath: { fontSize: 12, color: "#64748b", marginTop: 2 },
  fileSize: { fontSize: 11, color: "#94a3b8", fontWeight: 500, padding: "3px 8px", backgroundColor: "#f1f5f9", borderRadius: 6 },
  discoveryContent: { display: "flex", flexDirection: "column", gap: 14 },
  discoveryItem: { ...glassSurface, display: "flex", alignItems: "center", gap: 14, padding: 18, borderRadius: 10 },
  discoveryIcon: { fontSize: 26 },
  discoveryTitle: { fontSize: 15, fontWeight: 600, color: "#1e293b", marginBottom: 2 },
  discoveryDesc: { fontSize: 13, color: "#64748b" },
  detectedConfigCard: { background: "linear-gradient(135deg, rgba(239, 246, 255, 0.78) 0%, rgba(248, 250, 252, 0.58) 100%)", border: "1px solid rgba(147, 197, 253, 0.6)", borderRadius: 12, padding: 20, marginTop: 18, marginBottom: 20, boxShadow: "0 16px 38px rgba(37, 99, 235, 0.12), inset 0 1px 0 rgba(255, 255, 255, 0.66)", backdropFilter: "blur(14px) saturate(135%)", WebkitBackdropFilter: "blur(14px) saturate(135%)" },
  detectedConfigHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, marginBottom: 14 },
  detectedConfigTitle: { fontSize: 16, fontWeight: 700, color: "#1e3a8a", marginBottom: 4 },
  detectedConfigSubtitle: { fontSize: 13, color: "#475569", lineHeight: 1.5 },
  detectedConfigActions: { display: "flex", flexWrap: "wrap", gap: 12, marginBottom: 12 },
  detectedConfigChip: { padding: "10px 14px", borderRadius: 999, border: "1px solid rgba(147, 197, 253, 0.72)", background: "rgba(255, 255, 255, 0.7)", color: "#1e3a8a", fontSize: 13, fontWeight: 600, cursor: "default" },
  detectedConfigActionBtn: { padding: "10px 16px", borderRadius: 999, border: "1px solid var(--theme-accent, #2563eb)", background: "var(--theme-accent, #2563eb)", color: "#fff", fontSize: 13, fontWeight: 700, cursor: "pointer", transition: "all 0.2s ease" },
  detectedConfigActionBtnActive: { background: "var(--theme-accent, #1d4ed8)", borderColor: "var(--theme-accent, #1d4ed8)", boxShadow: "0 0 0 3px rgba(var(--theme-accent-rgb, 37, 99, 235), 0.15)" },
  detectedConfigNote: { fontSize: 12, color: "#475569", lineHeight: 1.5 },
  reportContainer: { display: "flex", flexDirection: "column", gap: 20 },
  reportSection: { ...glassSurface, borderRadius: 12, padding: 22 },
  reportTitle: { fontSize: 17, fontWeight: 700, color: "#1e293b", marginBottom: 18, paddingBottom: 12, borderBottom: "1px solid #e2e8f0", display: "flex", alignItems: "center", gap: 10 },
  reportGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 14 },
  reportItem: { display: "flex", flexDirection: "column", gap: 6 },
  reportLabel: { fontSize: 11, color: "#64748b", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.5px" },
  reportValue: { fontSize: 14, color: "#1e293b", fontWeight: 600 },
  testResults: { display: "flex", flexDirection: "column", gap: 10 },
  testItem: { ...glassSurface, display: "flex", justifyContent: "space-between", padding: "14px 18px", borderRadius: 10 },
  sonarqubeResults: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 16 },
  qualityItem: { ...glassSurface, display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 18px", borderRadius: 10 },
  logsContainer: { background: "#1e293b", color: "#10b981", fontFamily: "'JetBrains Mono', 'Fira Code', monospace", padding: 18, borderRadius: 10, maxHeight: 300, overflowY: "auto", fontSize: 12, lineHeight: 1.6, border: "1px solid #334155" },
  logEntry: { marginBottom: 6, padding: "3px 0", borderBottom: "1px solid rgba(255,255,255,0.05)" },
  issuesContainer: { display: "flex", flexDirection: "column", gap: 12 },
  issueItem: { ...glassSurface, padding: 18, borderRadius: 10 },
  issueHeader: { display: "flex", alignItems: "center", gap: 12, marginBottom: 10 },
  issueSeverity: { padding: "6px 12px", borderRadius: 12, fontSize: 11, fontWeight: 600, color: "#fff", textTransform: "uppercase" },
  issueCategory: { fontSize: 12, color: "#64748b", fontWeight: 600, textTransform: "uppercase" },
  issueStatus: { fontSize: 12, color: "#059669", fontWeight: 600, marginLeft: "auto" },
  issueMessage: { fontSize: 14, color: "#1e293b", marginBottom: 8, fontWeight: 500, lineHeight: 1.4 },
  issueFile: { fontSize: 12, color: "#2563eb", fontFamily: "'JetBrains Mono', monospace", backgroundColor: "#eff6ff", padding: "6px 12px", borderRadius: 6, display: "inline-block" },
  noIssues: { textAlign: "center", color: "#64748b", padding: 28, fontStyle: "italic", fontSize: 14 },
  noFilesMsg: { textAlign: "center", color: "#64748b", padding: 28, fontStyle: "italic", background: "rgba(248, 250, 252, 0.7)", borderRadius: 10, border: "1px dashed rgba(148, 163, 184, 0.42)", backdropFilter: "blur(12px) saturate(135%)", WebkitBackdropFilter: "blur(12px) saturate(135%)" },
  noLogs: { textAlign: "center", color: "#64748b", padding: 28, fontStyle: "italic" },

  // Animation styles
  animationContainer: { ...glassSurface, padding: 24, borderRadius: 12, marginTop: 20 },
  migrationAnimation: { maxWidth: 600, margin: "0 auto" },
  animationHeader: { textAlign: "center", marginBottom: 32 },
  migratingText: { fontSize: 24, fontWeight: 700, color: "#1e293b", marginBottom: 10 },
  versionTransition: { fontSize: 14, color: "#fff", padding: "10px 20px", background: "#2563eb", borderRadius: 20, display: "inline-block", fontWeight: 600 },
  animationSteps: { display: "flex", flexDirection: "column", gap: 14, marginBottom: 28 },
  animationStep: { ...glassSurface, display: "flex", alignItems: "center", gap: 14, padding: 18, borderRadius: 10 },
  stepIconAnimated: { fontSize: 22, minWidth: 22 },
  stepText: { flex: 1, fontSize: 14, fontWeight: 500, color: "#1e293b" },
  checkMarkAnimated: { fontSize: 18, color: "#059669" },
  animatedProgressSection: { marginBottom: 24 },
  animatedProgressHeader: { display: "flex", justifyContent: "space-between", marginBottom: 12, fontSize: 14, fontWeight: 600, color: "#1e293b" },
  animatedProgressBar: { width: "100%", height: 12, background: "#e5e7eb", borderRadius: 8, overflow: "hidden" },
  animatedProgressFill: { height: "100%", borderRadius: 8, transition: "width 0.4s ease", background: "linear-gradient(135deg, var(--theme-accent, #2563eb), var(--theme-accent-2, #06b6d4))" },
  statusMessages: { textAlign: "center" },
  currentStatus: { fontSize: 16, fontWeight: 600, color: "#1e293b", marginBottom: 10 },
  recentLog: { fontSize: 13, color: "#64748b", fontFamily: "'JetBrains Mono', monospace", background: "rgba(248, 250, 252, 0.7)", padding: "12px 16px", borderRadius: 8, border: "1px solid rgba(255, 255, 255, 0.38)", backdropFilter: "blur(12px) saturate(135%)", WebkitBackdropFilter: "blur(12px) saturate(135%)" },

  // Report styles
  changesGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 14 },
  changeItem: { ...glassSurface, display: "flex", alignItems: "center", gap: 14, padding: 18, borderRadius: 10 },
  changeIcon: { fontSize: 26 },
  changeTitle: { fontSize: 14, fontWeight: 600, color: "#1e293b", marginBottom: 4 },
  changeValue: { fontSize: 13, color: "#64748b" },
  dependenciesReport: { display: "flex", flexDirection: "column", gap: 10 },
  dependencyReportItem: { ...glassSurface, display: "grid", gridTemplateColumns: "1fr 200px 140px", gap: 14, alignItems: "center", padding: "14px 18px", borderRadius: 10 },
  dependencyName: { fontSize: 14, fontWeight: 600, color: "#1e293b", fontFamily: "'JetBrains Mono', monospace", wordBreak: "break-word" },
  dependencyChange: { fontSize: 13, color: "#64748b", textAlign: "center" },
  dependencyStatus: { padding: "6px 12px", borderRadius: 12, fontSize: 11, fontWeight: 600, textTransform: "uppercase", textAlign: "center" },
  noData: { textAlign: "center", color: "#64748b", padding: 28, fontStyle: "italic" },
  errorsSummary: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 14 },
  errorStat: { ...glassSurface, textAlign: "center", padding: 18, borderRadius: 10 },
  errorCount: { display: "block", fontSize: 26, fontWeight: 700, color: "#1e293b", marginBottom: 6 },
  errorLabel: { fontSize: 12, color: "#64748b", fontWeight: 600, textTransform: "uppercase" },
  businessLogicGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 14 },
  businessItem: { ...glassSurface, display: "flex", alignItems: "flex-start", gap: 14, padding: 18, borderRadius: 10 },
  businessIcon: { fontSize: 26, marginTop: 2 },
  businessTitle: { fontSize: 14, fontWeight: 600, color: "#1e293b", marginBottom: 6 },
  businessDesc: { fontSize: 13, color: "#64748b", lineHeight: 1.5 },
  sonarqubeGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 20, marginBottom: 20 },
  sonarqubeItem: { textAlign: "center" },
  qualityGate: { marginBottom: 18 },
  gateStatus: { display: "inline-block", padding: "12px 24px", borderRadius: 20, color: "#fff", fontSize: 14, fontWeight: 700, textTransform: "uppercase" },
  gateLabel: { display: "block", fontSize: 12, color: "#64748b", marginTop: 10, fontWeight: 600 },
  coverageMeter: { position: "relative" },
  coverageCircle: { width: 110, height: 110, borderRadius: "50%", background: "rgba(239, 246, 255, 0.72)", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", margin: "0 auto", border: "3px solid #2563eb", backdropFilter: "blur(12px) saturate(135%)", WebkitBackdropFilter: "blur(12px) saturate(135%)" },
  coveragePercent: { fontSize: 26, fontWeight: 700, color: "#2563eb" },
  coverageLabel: { fontSize: 11, color: "#64748b", fontWeight: 600, marginTop: 2 },
  qualityMetrics: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 14 },
  metricItem: { ...glassSurface, textAlign: "center", padding: 14, borderRadius: 10 },
  metricValue: { display: "block", fontSize: 22, fontWeight: 700, marginBottom: 6, color: "#1e293b" },
  metricLabel: { fontSize: 11, color: "#64748b", fontWeight: 600, textTransform: "uppercase" },
  testReportGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 14, marginBottom: 18 },
  testMetric: { ...glassSurface, textAlign: "center", padding: 18, borderRadius: 10 },
  testValue: { display: "block", fontSize: 24, fontWeight: 700, color: "var(--theme-accent, #2563eb)", marginBottom: 6 },
  testLabel: { fontSize: 12, color: "#64748b", fontWeight: 600, textTransform: "uppercase" },
  testStatus: { display: "flex", alignItems: "center", gap: 10, padding: 14, background: "rgba(220, 252, 231, 0.76)", borderRadius: 10, border: "1px solid rgba(134, 239, 172, 0.68)", backdropFilter: "blur(12px) saturate(135%)", WebkitBackdropFilter: "blur(12px) saturate(135%)" },
  testStatusIcon: { fontSize: 18 },
  jmeterGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14 },
  jmeterItem: { ...glassSurface, display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 20px", borderRadius: 10 },
  jmeterLabel: { fontSize: 14, color: "#64748b" },
  jmeterValue: { fontSize: 16, fontWeight: 700, color: "#1e293b" },
};
