import React from "react";

export const styles: { [key: string]: React.CSSProperties } = {
  container: { height: "100%", display: "flex", flexDirection: "column", flex: 1, width: "100%", maxWidth: "100vw", margin: 0, padding: 0, background: "linear-gradient(135deg, var(--background) 0%, var(--card) 50%, var(--background) 100%)", fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif", overflow: "hidden" },
  appLayout: {
    display: "grid",
    gridTemplateColumns: "250px 1fr",
    height: "100%",
    flex: 1,
    width: "100%"
  },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "18px 40px", width: "100%", boxSizing: "border-box", background: "var(--glass-bg)", borderBottom: "1px solid var(--border)", backdropFilter: "var(--glass-blur)" },
  logo: { display: "flex", alignItems: "center", gap: 12 },
  stepIndicatorContainer: { background: "var(--card)", borderRight: "1px solid var(--border)", padding: "32px 24px", width: "100%", boxSizing: "border-box", height: "100%", overflowY: "auto", boxShadow: "10px 0 30px rgba(0, 0, 0, 0.02)", backdropFilter: "var(--glass-blur)" },
  stepIndicator: { display: "flex", flexDirection: "column", gap: 0, justifyContent: "flex-start", alignItems: "stretch", width: "100%", margin: 0, position: "relative" },
  stepItem: { display: "flex", alignItems: "center", gap: 8, padding: "6px 12px", borderRadius: 8, transition: "all 0.3s ease", cursor: "pointer", whiteSpace: "nowrap" },
  stepCircle: { width: 36, height: 36, borderRadius: 10, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, fontWeight: 700, transition: "all 0.3s ease", position: "relative", zIndex: 2, border: "1px solid var(--border)" },
  stepLabel: { display: "flex", flexDirection: "column" },
  stepFlowItem: { display: "flex", flexDirection: "row", alignItems: "flex-start", gap: 12, minWidth: 0, padding: "10px 8px", borderRadius: 10, transition: "all 0.3s ease", position: "relative", zIndex: 2 },
  stepFlowLabel: { display: "flex", flexDirection: "column", alignItems: "flex-start", textAlign: "left", gap: 4, paddingTop: 1 },
  stepStatusPill: { display: "inline-flex", alignItems: "center", justifyContent: "center", minHeight: 20, padding: "3px 8px", borderRadius: 999, border: "1px solid var(--border)", fontSize: 10, fontWeight: 700, lineHeight: 1, textTransform: "uppercase" },
  stepFlowConnector: { width: 4, height: 32, marginTop: -2, marginBottom: -2, marginLeft: 24, borderRadius: 999, overflow: "hidden", position: "relative", background: "var(--border)", transition: "background 0.35s ease" },
  stepFlowConnectorFill: { position: "absolute", inset: 0, borderRadius: 999, transition: "height 0.45s ease" },
  main: { width: "100%", maxWidth: 1280, margin: "0 auto", padding: "32px 40px 40px", height: "100%", maxHeight: "100%", overflowY: "auto", boxSizing: "border-box" },
  
  card: { background: "var(--card)", borderRadius: 16, padding: "32px 36px", boxShadow: "var(--shadow-lg)", marginBottom: 24, width: "100%", boxSizing: "border-box", border: "1px solid var(--border)", backdropFilter: "var(--glass-blur)", transition: "background-color 0.3s ease, border-color 0.3s ease, box-shadow 0.3s ease, transform 0.3s ease" },
  
  stepHeader: { display: "flex", alignItems: "flex-start", gap: 14, marginBottom: 28, paddingBottom: 20, borderBottom: "1px solid var(--border)", flexWrap: "wrap" },
  stepIcon: { fontSize: 28, width: 48, height: 48, borderRadius: 12, background: "linear-gradient(135deg, rgba(59, 130, 246, 0.1) 0%, rgba(59, 130, 246, 0.05) 100%)", color: "var(--primary)", display: "inline-flex", alignItems: "center", justifyContent: "center", border: "1px solid rgba(59, 130, 246, 0.2)" },
  title: { fontSize: 24, fontWeight: 800, marginBottom: 8, color: "var(--foreground)", letterSpacing: "-0.5px" },
  subtitle: { fontSize: 14, color: "var(--muted-foreground)", margin: 0, lineHeight: 1.5 },
  sectionTitle: { fontSize: 15, fontWeight: 800, color: "var(--foreground)", marginBottom: 16, marginTop: 24, display: "flex", alignItems: "center", gap: 8, textTransform: "uppercase", letterSpacing: "0.3px" },
  field: { marginBottom: 22, width: "100%", boxSizing: "border-box" },
  label: { fontWeight: 600, fontSize: 14, marginBottom: 10, display: "block", color: "var(--foreground)" },
  input: { width: "100%", padding: "13px 16px", fontSize: 14, borderRadius: 10, border: "1px solid var(--border)", boxSizing: "border-box", transition: "all 0.3s ease", backgroundColor: "var(--card)", color: "var(--foreground)", boxShadow: "var(--shadow-sm)" },
  select: { width: "100%", padding: "13px 16px", fontSize: 14, borderRadius: 10, border: "1px solid var(--border)", backgroundColor: "var(--card)", color: "var(--foreground)", transition: "all 0.3s ease", cursor: "pointer", boxShadow: "var(--shadow-sm)" },
  helpText: { fontSize: 13, color: "var(--muted-foreground)", marginTop: 8, lineHeight: 1.4 },
  infoButtonContainer: { position: "relative", display: "inline-block", zIndex: 100 },
  infoButton: { width: 22, height: 22, borderRadius: "50%", background: "rgba(96, 165, 250, 0.15)", border: "1px solid rgba(96, 165, 250, 0.3)", cursor: "pointer", fontSize: 12, color: "var(--primary)", display: "inline-flex", alignItems: "center", justifyContent: "center", transition: "all 0.3s ease", padding: 0, fontWeight: 600 },
  tooltip: { display: "none", position: "absolute", bottom: "calc(100% + 10px)", left: 0, width: 300, background: "var(--card)", color: "var(--foreground)", padding: "14px 16px", borderRadius: 10, fontSize: 13, zIndex: 1001, boxShadow: "var(--shadow-lg)", border: "1px solid var(--border)" },
  link: { color: "var(--primary)", textDecoration: "none", fontWeight: 600, transition: "color 0.3s ease" },
  infoBox: { background: "rgba(59, 130, 246, 0.08)", border: "1px solid rgba(59, 130, 246, 0.18)", borderRadius: 10, padding: 18, marginBottom: 22, fontSize: 14, color: "var(--primary)", width: "100%", boxSizing: "border-box", lineHeight: 1.5 },
  warningBox: { background: "rgba(217, 119, 6, 0.08)", border: "1px solid rgba(217, 119, 6, 0.18)", borderRadius: 10, padding: 18, marginBottom: 22, width: "100%", boxSizing: "border-box" },
  warningTitle: { fontWeight: 600, marginBottom: 10, color: "#fb923c", fontSize: 14 },
  warningList: { margin: 0, paddingLeft: 18, fontSize: 14, color: "var(--foreground)", lineHeight: 1.6 },
  errorBanner: { background: "rgba(239, 68, 68, 0.1)", border: "1px solid rgba(239, 68, 68, 0.2)", borderRadius: 10, padding: "14px 18px", marginBottom: 22, display: "flex", justifyContent: "space-between", alignItems: "center", color: "var(--destructive)", width: "100%", boxSizing: "border-box" },
  errorClose: { background: "none", border: "none", fontSize: 18, cursor: "pointer", color: "var(--destructive)" },
  errorBox: { background: "rgba(239, 68, 68, 0.1)", border: "1px solid rgba(239, 68, 68, 0.2)", borderRadius: 10, padding: "16px 18px", marginBottom: 22, color: "var(--destructive)", width: "100%", boxSizing: "border-box" },
  btnRow: { display: "flex", gap: 14, marginTop: 28, justifyContent: "flex-end", flexWrap: "wrap" },
  primaryBtn: { background: "var(--primary-gradient)", color: "white", border: "none", borderRadius: 10, padding: "13px 24px", fontWeight: 700, cursor: "pointer", fontSize: 14, transition: "all 0.2s ease", boxShadow: "0 4px 14px rgba(59, 130, 246, 0.3)" },
  secondaryBtn: { background: "var(--card)", color: "var(--foreground)", border: "1px solid var(--border)", borderRadius: 10, padding: "13px 24px", fontWeight: 600, cursor: "pointer", fontSize: 14, transition: "all 0.2s ease", boxShadow: "var(--shadow-sm)" },
  row: { display: "flex", gap: 22, flexWrap: "wrap" },
  loadingBox: { display: "flex", alignItems: "center", justifyContent: "center", gap: 14, padding: 48, color: "var(--primary)", fontWeight: 500, fontSize: 15 },
  spinner: { width: 28, height: 28, border: "3px solid rgba(148, 163, 184, 0.15)", borderTop: "3px solid var(--primary)", borderRadius: "50%", animation: "spin 0.8s linear infinite" },
  repoList: { display: "flex", flexDirection: "column", gap: 10, maxHeight: 300, overflowY: "auto", paddingRight: 8 },
  repoItem: { display: "flex", alignItems: "center", gap: 14, padding: "16px 18px", border: "1px solid var(--border)", borderRadius: 10, cursor: "pointer", transition: "all 0.3s ease", backgroundColor: "var(--card)", boxShadow: "var(--shadow-sm)" },
  repoIcon: { fontSize: 20 },
  repoInfo: { flex: 1 },
  repoName: { fontWeight: 600, fontSize: 14, color: "var(--foreground)" },
  repoPath: { fontSize: 12, color: "var(--muted-foreground)", marginTop: 2 },
  repoLanguage: { fontSize: 11, padding: "5px 12px", background: "rgba(59, 130, 246, 0.12)", color: "var(--primary)", borderRadius: 14, fontWeight: 600 },
  arrow: { fontSize: 16, color: "var(--primary)" },
  emptyText: { textAlign: "center", color: "var(--muted-foreground)", padding: 48, fontSize: 14 },
  selectedRepoBox: { display: "flex", alignItems: "center", gap: 14, padding: "14px 18px", background: "rgba(59, 130, 246, 0.06)", borderRadius: 10, marginBottom: 22, border: "1px solid rgba(59, 130, 246, 0.18)" },
  changeBtn: { marginLeft: "auto", background: "none", border: "none", color: "var(--primary)", cursor: "pointer", fontSize: 13, fontWeight: 600, transition: "color 0.3s ease" },
  riskBadge: { display: "inline-block", padding: "10px 18px", borderRadius: 18, fontSize: 13, fontWeight: 600, marginBottom: 16 },
  assessmentGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 18, marginBottom: 22 },
  assessmentItem: { background: "var(--card)", padding: 20, borderRadius: 10, textAlign: "center", border: "1px solid var(--border)", boxShadow: "var(--shadow-sm)" },
  assessmentLabel: { fontSize: 11, color: "var(--muted-foreground)", marginBottom: 10, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.5px" },
  assessmentValue: { fontSize: 24, fontWeight: 700, color: "var(--foreground)" },
  structureBox: { background: "var(--card)", padding: 20, borderRadius: 12, marginBottom: 22, border: "1px solid var(--border)" },
  structureTitle: { fontSize: 14, fontWeight: 600, marginBottom: 14, color: "var(--foreground)" },
  structureGrid: { display: "flex", gap: 16, flexWrap: "wrap" },
  structureFound: { color: "#16a34a", fontWeight: 600 },
  structureMissing: { color: "var(--muted-foreground)", fontWeight: 500 },
  dependenciesBox: { marginBottom: 22 },
  dependenciesList: { background: "var(--card)", borderRadius: 12, padding: 16, border: "1px solid var(--border)" },
  dependencyItem: { display: "flex", justifyContent: "space-between", padding: "12px 0", borderBottom: "1px solid var(--border)", fontSize: 13 },
  dependencyVersion: { color: "var(--primary)", fontFamily: "'JetBrains Mono', monospace", fontWeight: 500 },
  moreItems: { textAlign: "center", color: "var(--primary)", fontSize: 12, paddingTop: 12, fontWeight: 600 },
  radioGroup: { display: "flex", flexDirection: "column", gap: 12 },
  radioLabel: { display: "flex", alignItems: "flex-start", gap: 14, padding: 18, border: "1px solid var(--border)", borderRadius: 10, cursor: "pointer", transition: "all 0.3s ease", backgroundColor: "var(--card)", boxShadow: "var(--shadow-sm)" },
  radio: { marginTop: 4, accentColor: "#3b82f6" },
  checkbox: { width: 18, height: 18, accentColor: "#3b82f6", cursor: "pointer" },
  frameworkGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 16 },
  frameworkItem: { display: "flex", alignItems: "center", gap: 14, padding: 18, border: "1px solid var(--border)", borderRadius: 10, cursor: "pointer", background: "var(--card)", transition: "all 0.3s ease", boxShadow: "var(--shadow-sm)" },
  detectedBadge: { marginLeft: "auto", fontSize: 11, padding: "5px 12px", background: "#4ade80", color: "#0f172a", borderRadius: 14, fontWeight: 600 },
  conversionGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: 20,
    marginTop: 20
  },
  conversionItem: {
    position: "relative",
    display: "flex",
    alignItems: "flex-start",
    gap: 16,
    padding: "24px",
    minHeight: "140px",
    borderRadius: 16,
    border: "2px solid var(--border)",
    background: "var(--card)",
    cursor: "pointer",
    transition: "all 0.3s ease",
    boxShadow: "var(--shadow-sm)"
  },
  conversionItemSelected: {
    border: "2px solid var(--primary)",
    background: "rgba(59, 130, 246, 0.04)",
    boxShadow: "0 8px 24px rgba(37,99,235,0.08)"
  },
  conversionIcon: {
    width: 44,
    height: 44,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 22,
    background: "rgba(59, 130, 246, 0.1)",
    color: "var(--primary)",
    flexShrink: 0
  },
  conversionTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "var(--foreground)",
    marginBottom: 8,
    lineHeight: 1.3
  },
  conversionDescription: {
    fontSize: 13,
    color: "var(--muted-foreground)",
    lineHeight: 1.5
  },
  statusBadge: {
    position: "absolute",
    top: 14,
    right: 14,
    padding: "4px 10px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 600
  },
  checkMark: { position: "absolute", top: 12, right: 12, color: "#16a34a", fontWeight: 700, fontSize: 18 },
  optionsGrid: { display: "flex", flexDirection: "column", gap: 16 },
  optionItem: { display: "flex", alignItems: "flex-start", gap: 16, padding: 20, border: "1px solid var(--border)", borderRadius: 10, cursor: "pointer", background: "var(--card)", transition: "all 0.3s ease", boxShadow: "var(--shadow-sm)" },
  progressSection: { marginBottom: 28 },
  progressHeader: { display: "flex", justifyContent: "space-between", marginBottom: 12, fontSize: 14, fontWeight: 600, color: "var(--foreground)" },
  progressBar: { width: "100%", height: 12, background: "var(--border)", borderRadius: 8, overflow: "hidden", border: "1px solid var(--border)" },
  progressFill: { height: "100%", background: "var(--primary-gradient)", borderRadius: 8, transition: "width 0.4s ease" },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 18, marginBottom: 28 },
  statBox: { background: "var(--card)", padding: 24, borderRadius: 12, textAlign: "center", border: "1px solid var(--border)", boxShadow: "var(--shadow-sm)" },
  statValue: { fontSize: 32, fontWeight: 700, color: "var(--primary)" },
  statLabel: { fontSize: 12, color: "var(--muted-foreground)", marginTop: 10, fontWeight: 600, textTransform: "uppercase" },
  successBox: { background: "rgba(74, 222, 128, 0.1)", border: "1px solid rgba(74, 222, 128, 0.2)", borderRadius: 14, padding: 32, textAlign: "center", marginBottom: 28 },
  successTitle: { fontSize: 22, fontWeight: 700, color: "#16a34a", marginBottom: 14 },
  repoLink: { display: "inline-block", color: "var(--primary)", fontWeight: 600, textDecoration: "none", fontSize: 14, padding: "12px 24px", background: "rgba(59, 130, 246, 0.08)", borderRadius: 10, border: "1px solid rgba(59, 130, 246, 0.18)", transition: "all 0.3s ease" },
  connectLayout: { display: "block", minHeight: 0 },
  connectFormPanel: { padding: "36px 38px", background: "var(--card)" },
  connectSummaryPanel: { padding: "36px 30px", background: "var(--background)", borderLeft: "1px solid var(--border)", display: "flex", flexDirection: "column", justifyContent: "center" },
  connectEyebrow: { display: "inline-flex", alignItems: "center", height: 24, padding: "0 10px", borderRadius: 999, background: "rgba(59, 130, 246, 0.12)", color: "var(--primary)", fontSize: 11, fontWeight: 800, textTransform: "uppercase", marginBottom: 18 },
  connectHeaderRow: { display: "flex", alignItems: "flex-start", gap: 14, marginBottom: 30 },
  connectInputCard: { padding: 22, border: "1px solid var(--border)", borderRadius: 12, background: "var(--card)", boxShadow: "var(--shadow-sm)", marginBottom: 18 },
  connectInputWrap: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) auto", gap: 12, alignItems: "center" },
  connectInput: { height: 48, fontSize: 15 },
  connectInlineBtn: { height: 48, padding: "0 22px", whiteSpace: "nowrap" },
  connectHelpGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 12, marginTop: 14 },
  connectFormatBox: { padding: 14, borderRadius: 10, border: "1px solid var(--border)", background: "var(--background)", color: "var(--muted-foreground)", fontSize: 12, lineHeight: 1.6 },
  connectFormatTitle: { color: "var(--foreground)", fontWeight: 800, fontSize: 12, marginBottom: 4 },
  connectNote: { fontSize: 12, color: "var(--muted-foreground)", marginTop: 12, lineHeight: 1.5 },
  connectValidation: { marginTop: 12, padding: "10px 12px", border: "1px solid", borderRadius: 10, fontSize: 12, fontWeight: 700 },
  connectSummaryBadge: { alignSelf: "flex-start", padding: "7px 11px", borderRadius: 999, background: "var(--card)", border: "1px solid var(--border)", color: "var(--primary)", fontSize: 11, fontWeight: 800, textTransform: "uppercase", marginBottom: 16 },
  connectSummaryTitle: { margin: "0 0 22px", color: "var(--foreground)", fontSize: 24, lineHeight: 1.18 },
  connectSummaryList: { display: "flex", flexDirection: "column", gap: 14 },
  connectSummaryItem: { display: "flex", gap: 12, alignItems: "flex-start" },
  connectSummaryIndex: { width: 28, height: 28, borderRadius: 8, display: "inline-flex", alignItems: "center", justifyContent: "center", background: "var(--primary)", color: "white", fontSize: 12, fontWeight: 800, flexShrink: 0 },
  connectSummaryItemTitle: { color: "var(--foreground)", fontWeight: 800, fontSize: 13, marginBottom: 3 },
  connectSummaryItemText: { color: "var(--muted-foreground)", fontSize: 12, lineHeight: 1.45 },
  connectionModes: { display: "flex", gap: 16, marginBottom: 22 },
  modeButton: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 10, padding: 22, border: "1px solid var(--border)", borderRadius: 12, background: "var(--card)", cursor: "pointer", transition: "all 0.3s ease", fontWeight: 500, boxShadow: "var(--shadow-sm)" },
  modeButtonActive: { border: "1px solid var(--primary)", background: "rgba(59, 130, 246, 0.05)" },
  modeIcon: { fontSize: 28 },
  modeTitle: { fontWeight: 600, fontSize: 14, color: "var(--foreground)" },
  modeDesc: { fontSize: 12, color: "var(--muted-foreground)", textAlign: "center", lineHeight: 1.4 },
  fileList: { display: "flex", flexDirection: "column", gap: 10, maxHeight: 380, overflowY: "auto", border: "1px solid var(--border)", borderRadius: 12, padding: 16, background: "var(--card)" },
  breadcrumb: { display: "flex", alignItems: "center", gap: 14, marginBottom: 16, padding: "12px 16px", background: "rgba(59, 130, 246, 0.08)", borderRadius: 10, border: "1px solid rgba(59, 130, 246, 0.18)" },
  backBtn: { background: "none", border: "none", color: "var(--primary)", cursor: "pointer", fontSize: 14, fontWeight: 600, transition: "color 0.3s ease" },
  fileItem: { display: "flex", alignItems: "center", gap: 14, padding: "16px 18px", border: "1px solid var(--border)", borderRadius: 10, cursor: "pointer", transition: "all 0.3s ease", backgroundColor: "var(--card)" },
  fileIcon: { fontSize: 20 },
  fileInfo: { flex: 1 },
  fileName: { fontWeight: 600, fontSize: 14, color: "var(--foreground)" },
  filePath: { fontSize: 12, color: "var(--muted-foreground)", marginTop: 2 },
  fileSize: { fontSize: 11, color: "var(--muted-foreground)", fontWeight: 500, padding: "4px 10px", backgroundColor: "var(--background)", borderRadius: 6 },
  discoveryContent: { display: "flex", flexDirection: "column", gap: 16 },
  discoveryItem: { display: "flex", alignItems: "center", gap: 16, padding: 20, background: "var(--card)", borderRadius: 12, border: "1px solid var(--border)" },
  discoveryIcon: { fontSize: 28 },
  discoveryTitle: { fontSize: 15, fontWeight: 600, color: "var(--foreground)", marginBottom: 2 },
  discoveryDesc: { fontSize: 13, color: "var(--muted-foreground)" },
  detectedConfigCard: { background: "rgba(59, 130, 246, 0.06)", border: "1px solid rgba(59, 130, 246, 0.18)", borderRadius: 14, padding: 24, marginTop: 20, marginBottom: 22 },
  detectedConfigHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 18, marginBottom: 16 },
  detectedConfigTitle: { fontSize: 16, fontWeight: 700, color: "var(--primary)", marginBottom: 4 },
  detectedConfigSubtitle: { fontSize: 13, color: "var(--foreground)", lineHeight: 1.5 },
  detectedConfigActions: { display: "flex", flexWrap: "wrap", gap: 12, marginBottom: 12 },
  detectedConfigChip: { padding: "12px 16px", borderRadius: 999, border: "1px solid rgba(96, 165, 250, 0.3)", background: "rgba(96, 165, 250, 0.1)", color: "var(--primary)", fontSize: 13, fontWeight: 600, cursor: "default" },
  detectedConfigActionBtn: { padding: "12px 18px", borderRadius: 999, border: "none", background: "var(--primary-gradient)", color: "white", fontSize: 13, fontWeight: 700, cursor: "pointer", transition: "all 0.3s ease", boxShadow: "0 6px 20px rgba(59, 130, 246, 0.25)" },
  detectedConfigActionBtnActive: { background: "var(--primary-gradient)", boxShadow: "0 0 0 3px rgba(59, 130, 246, 0.2)" },
  detectedConfigNote: { fontSize: 12, color: "var(--muted-foreground)", lineHeight: 1.5 },
  reportContainer: { display: "flex", flexDirection: "column", gap: 24 },
  reportSection: { background: "var(--card)", borderRadius: 14, padding: 24, border: "1px solid var(--border)" },
  reportTitle: { fontSize: 17, fontWeight: 700, color: "var(--foreground)", marginBottom: 20, paddingBottom: 14, borderBottom: "1px solid var(--border)", display: "flex", alignItems: "center", gap: 10 },
  reportGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 16 },
  reportItem: { display: "flex", flexDirection: "column", gap: 8 },
  reportLabel: { fontSize: 11, color: "var(--muted-foreground)", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.5px" },
  reportValue: { fontSize: 14, color: "var(--foreground)", fontWeight: 600 },
  testResults: { display: "flex", flexDirection: "column", gap: 12 },
  testItem: { display: "flex", justifyContent: "space-between", padding: "16px 20px", background: "var(--card)", borderRadius: 10, border: "1px solid var(--border)" },
  sonarqubeResults: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 18 },
  qualityItem: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "18px 20px", background: "var(--card)", borderRadius: 10, border: "1px solid var(--border)" },
  logsContainer: { background: "var(--card)", color: "#16a34a", fontFamily: "'JetBrains Mono', 'Fira Code', monospace", padding: 20, borderRadius: 12, maxHeight: 300, overflowY: "auto", fontSize: 12, lineHeight: 1.6, border: "1px solid var(--border)", boxShadow: "var(--shadow-sm)" },
  logEntry: { marginBottom: 6, padding: "3px 0", borderBottom: "1px solid var(--border)" },
  issuesContainer: { display: "flex", flexDirection: "column", gap: 14 },
  issueItem: { padding: 20, background: "var(--card)", borderRadius: 10, border: "1px solid var(--border)" },
  issueHeader: { display: "flex", alignItems: "center", gap: 14, marginBottom: 12 },
  issueSeverity: { padding: "8px 14px", borderRadius: 14, fontSize: 11, fontWeight: 600, color: "#fff", textTransform: "uppercase" },
  issueCategory: { fontSize: 12, color: "var(--muted-foreground)", fontWeight: 600, textTransform: "uppercase" },
  issueStatus: { fontSize: 12, color: "#16a34a", fontWeight: 600, marginLeft: "auto" },
  issueMessage: { fontSize: 14, color: "var(--foreground)", marginBottom: 10, fontWeight: 500, lineHeight: 1.4 },
  issueFile: { fontSize: 12, color: "var(--primary)", fontFamily: "'JetBrains Mono', monospace", backgroundColor: "rgba(59, 130, 246, 0.12)", padding: "8px 14px", borderRadius: 8, display: "inline-block", border: "1px solid rgba(59, 130, 246, 0.2)" },
  noIssues: { textAlign: "center", color: "var(--muted-foreground)", padding: 32, fontStyle: "italic", fontSize: 14 },
  noFilesMsg: { textAlign: "center", color: "var(--muted-foreground)", padding: 32, fontStyle: "italic", background: "var(--card)", borderRadius: 10, border: "1px dashed var(--border)" },
  noLogs: { textAlign: "center", color: "var(--muted-foreground)", padding: 32, fontStyle: "italic" },

  // Animation styles
  animationContainer: { padding: 28, background: "var(--card)", borderRadius: 14, marginTop: 24, border: "1px solid var(--border)" },
  migrationAnimation: { maxWidth: 600, margin: "0 auto" },
  animationHeader: { textAlign: "center", marginBottom: 36 },
  migratingText: { fontSize: 26, fontWeight: 700, color: "var(--foreground)", marginBottom: 12 },
  versionTransition: { fontSize: 14, color: "#fff", padding: "12px 24px", background: "var(--primary-gradient)", borderRadius: 24, display: "inline-block", fontWeight: 600, boxShadow: "0 6px 20px rgba(59, 130, 246, 0.25)" },
  animationSteps: { display: "flex", flexDirection: "column", gap: 16, marginBottom: 32 },
  animationStep: { display: "flex", alignItems: "center", gap: 16, padding: 20, background: "var(--card)", borderRadius: 10, border: "1px solid var(--border)" },
  stepIconAnimated: { fontSize: 22, minWidth: 22 },
  stepText: { flex: 1, fontSize: 14, fontWeight: 500, color: "var(--foreground)" },
  checkMarkAnimated: { fontSize: 18, color: "#16a34a" },
  animatedProgressSection: { marginBottom: 28 },
  animatedProgressHeader: { display: "flex", justifyContent: "space-between", marginBottom: 14, fontSize: 14, fontWeight: 600, color: "var(--foreground)" },
  animatedProgressBar: { width: "100%", height: 14, background: "var(--border)", borderRadius: 8, overflow: "hidden", border: "1px solid var(--border)" },
  animatedProgressFill: { height: "100%", borderRadius: 8, transition: "width 0.4s ease", background: "var(--primary-gradient)" },
  statusMessages: { textAlign: "center" },
  currentStatus: { fontSize: 16, fontWeight: 600, color: "var(--foreground)", marginBottom: 12 },
  recentLog: { fontSize: 13, color: "var(--muted-foreground)", fontFamily: "'JetBrains Mono', monospace", background: "var(--card)", padding: "14px 18px", borderRadius: 8, border: "1px solid var(--border)" },

  // Report styles
  changesGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 16 },
  changeItem: { display: "flex", alignItems: "center", gap: 16, padding: 20, background: "var(--card)", borderRadius: 10, border: "1px solid var(--border)" },
  changeIcon: { fontSize: 28 },
  changeTitle: { fontSize: 14, fontWeight: 600, color: "var(--foreground)", marginBottom: 4 },
  changeValue: { fontSize: 13, color: "var(--muted-foreground)" },
  dependenciesReport: { display: "flex", flexDirection: "column", gap: 12 },
  dependencyReportItem: { display: "grid", gridTemplateColumns: "1fr 200px 140px", gap: 16, alignItems: "center", padding: "16px 20px", background: "var(--card)", borderRadius: 10, border: "1px solid var(--border)" },
  dependencyName: { fontSize: 14, fontWeight: 600, color: "var(--foreground)", fontFamily: "'JetBrains Mono', monospace", wordBreak: "break-word" },
  dependencyChange: { fontSize: 13, color: "var(--muted-foreground)", textAlign: "center" },
  dependencyStatus: { padding: "8px 14px", borderRadius: 14, fontSize: 11, fontWeight: 600, textTransform: "uppercase", textAlign: "center", color: "#fff" },
  noData: { textAlign: "center", color: "var(--muted-foreground)", padding: 32, fontStyle: "italic" },
  errorsSummary: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 16 },
  errorStat: { textAlign: "center", padding: 20, background: "var(--card)", borderRadius: 10, border: "1px solid var(--border)" },
  errorCount: { display: "block", fontSize: 28, fontWeight: 700, color: "var(--foreground)", marginBottom: 8 },
  errorLabel: { fontSize: 12, color: "var(--muted-foreground)", fontWeight: 600, textTransform: "uppercase" },
  businessLogicGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 16 },
  businessItem: { display: "flex", alignItems: "flex-start", gap: 16, padding: 20, background: "var(--card)", borderRadius: 10, border: "1px solid var(--border)" },
  businessIcon: { fontSize: 28, marginTop: 2 },
  businessTitle: { fontSize: 14, fontWeight: 600, color: "var(--foreground)", marginBottom: 8 },
  businessDesc: { fontSize: 13, color: "var(--muted-foreground)", lineHeight: 1.5 },
  sonarqubeGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 22, marginBottom: 24 },
  sonarqubeItem: { textAlign: "center" },
  qualityGate: { marginBottom: 20 },
  gateStatus: { display: "inline-block", padding: "14px 28px", borderRadius: 24, color: "#fff", fontSize: 14, fontWeight: 700, textTransform: "uppercase" },
  gateLabel: { display: "block", fontSize: 12, color: "var(--muted-foreground)", marginTop: 12, fontWeight: 600 },
  coverageMeter: { position: "relative" },
  coverageCircle: { width: 120, height: 120, borderRadius: "50%", background: "rgba(59, 130, 246, 0.08)", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", margin: "0 auto", border: "3px solid rgba(96, 165, 250, 0.3)" },
  coveragePercent: { fontSize: 28, fontWeight: 700, color: "var(--primary)" },
  coverageLabel: { fontSize: 11, color: "var(--muted-foreground)", fontWeight: 600, marginTop: 4 },
  qualityMetrics: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 16 },
  metricItem: { textAlign: "center", padding: 16, background: "var(--card)", borderRadius: 10, border: "1px solid var(--border)" },
  metricValue: { display: "block", fontSize: 24, fontWeight: 700, marginBottom: 8, color: "var(--foreground)" },
  metricLabel: { fontSize: 11, color: "var(--muted-foreground)", fontWeight: 600, textTransform: "uppercase" },
  testReportGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 16, marginBottom: 20 },
  testMetric: { textAlign: "center", padding: 20, background: "var(--card)", borderRadius: 10, border: "1px solid var(--border)" },
  testValue: { display: "block", fontSize: 26, fontWeight: 700, color: "var(--primary)", marginBottom: 8 },
  testLabel: { fontSize: 12, color: "var(--muted-foreground)", fontWeight: 600, textTransform: "uppercase" },
  testStatus: { display: "flex", alignItems: "center", gap: 12, padding: 16, background: "rgba(74, 222, 128, 0.1)", borderRadius: 10, border: "1px solid rgba(74, 222, 128, 0.2)" },
  testStatusIcon: { fontSize: 20 },
  jmeterGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 16 },
  jmeterItem: { textAlign: "center", padding: 20, background: "var(--card)", borderRadius: 10, border: "1px solid var(--border)", boxShadow: "var(--shadow-sm)" },
  jmeterLabel: { fontSize: 12, color: "var(--muted-foreground)", fontWeight: 600, textTransform: "uppercase", display: "block", marginBottom: 8 },
  jmeterValue: { display: "block", fontSize: 24, fontWeight: 700, color: "var(--foreground)" },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(280px, 1fr))",
    gap: "18px",
    width: "100%",
    marginTop: "20px"
  },
  conversionCard: {
    position: "relative",
    background: "#ffffff",
    border: "2px solid #dbe4f0",
    borderRadius: "20px",
    padding: "18px",
    minHeight: "140px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    boxShadow: "0 2px 6px rgba(15,23,42,0.04)",
    overflow: "hidden"
  },
  selectedConversionCard: {
    border: "3px solid #2563eb",
    background: "#eef4ff",
    boxShadow: "0 6px 18px rgba(37,99,235,0.12)"
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "10px"
  },
  iconBox: {
    width: "40px",
    height: "40px",
    borderRadius: "12px",
    background: "#eff6ff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "18px",
    flexShrink: 0
  },
  content: {
    flex: 1,
    minWidth: 0
  },
  cardTitle: {
    margin: 0,
    fontSize: "16px",
    fontWeight: 700,
    color: "#0f172a",
    lineHeight: "1.3"
  },
  cardDesc: {
    margin: 0,
    fontSize: "13px",
    color: "#64748b",
    lineHeight: "1.5"
  },
  badge: {
    position: "absolute",
    top: "12px",
    right: "12px",
    padding: "6px 14px",
    borderRadius: "999px",
    fontSize: "11px",
    fontWeight: 600,
    whiteSpace: "nowrap"
  },
  timerCard: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 18px",
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "14px",
    boxShadow: "0 6px 18px rgba(15,23,42,0.08)",
    minWidth: "260px",
    maxWidth: "320px",
  },
  timerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  timerDot: {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    background: "#22c55e",
    boxShadow: "0 0 10px rgba(34,197,94,.6)",
  },
  timerTitle: {
    fontSize: "14px",
    fontWeight: 600,
    color: "#334155",
  },
  timerRight: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  timerIcon: {
    fontSize: "16px",
  },
  timerValue: {
    fontSize: "18px",
    fontWeight: 700,
    fontFamily: "'SFMono-Regular', Consolas, monospace",
    color: "#2563eb",
    letterSpacing: "1px",
  },
};
