import type { RepoFile, RepoAnalysis, RepoInfo, ConversionType } from "../../types/migration";

export interface RepositoryDiscoveryProps {
  selectedRepo: RepoInfo | null;
  repoAnalysis: RepoAnalysis | null;
  analysisLoading: boolean;
  formattedAnalysisElapsed: string;
  isJavaProject: boolean | null;
  setStep: (val: number) => void;
  setSelectedRepo: (val: RepoInfo | null) => void;
  setRepoAnalysis: (val: RepoAnalysis | null) => void;
  setIsJavaProject: (val: boolean | null) => void;
  setRepoUrl: (val: string) => void;
  detectedFrameworks: { name: string; path: string; type: string }[];
  isHighRiskProject: boolean;
  setIsHighRiskProject: (val: boolean) => void;
  highRiskConfirmed: boolean;
  setHighRiskConfirmed: (val: boolean) => void;
  suggestedJavaVersion: string;
  setSuggestedJavaVersion: (val: string) => void;
  setSelectedSourceVersion: (val: string) => void;
  selectedSourceVersion: string;
  sourceVersionStatus: "detected" | "not_selected" | "unknown";
  setSourceVersionStatus: (val: "detected" | "not_selected" | "unknown") => void;
  setUserSelectedVersion: (val: string | null) => void;
  conversionTypes: ConversionType[];
  selectedConversions: string[];
  setSelectedConversions: (val: string[]) => void;
  currentPath: string;
  pathHistory: string[];
  navigateToRoot: () => void;
  showFileExplorer: boolean;
  setShowFileExplorer: (val: boolean) => void;
  navigateBack: () => void;
  repoFiles: RepoFile[];
  handleFileClick: (file: RepoFile) => void;
  selectedFile: RepoFile | null;
  setSelectedFile: (val: RepoFile | null) => void;
  fileLoading: boolean;
  isEditing: boolean;
  editedContent: string;
  setEditedContent: (val: string) => void;
  fileContent: string;
  viewingFrameworkFile: { name: string; path: string; content: string } | null;
  setViewingFrameworkFile: (val: { name: string; path: string; content: string } | null) => void;
  frameworkFileLoading: boolean;
  setFrameworkFileLoading: (val: boolean) => void;
  currentToken: string;
}
